### ISSUE TITLE
`make pdf` broken

### ISSUE THREAD

**Issue by eddelbuettel** [mlr-org/mlr3book#105]
Ubuntu 19.10, everything current, `make clean` done, remotes update done.  Yet

```
[...]
label: 98-appendix-004 (with options) 
List of 1
 $ echo: logi FALSE


   inline R code fragments


output file: mlr3book.knit.md

/home/edd/bin/pandoc +RTS -K512m -RTS mlr3book.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output mlr3book.tex --self-contained --table-of-contents --toc-depth 4 --number-sections --highlight-style haddock --pdf-engine xelatex --natbib --include-in-header preamble.tex --variable graphics --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmd/lua/latex-div.lua --wrap preserve --include-in-header /tmp/RtmpXmq6Jr/rmarkdown-str1e8b5f04364e.html --variable tables=yes --standalone 
! Argument of \@sect has an extra }.
<inserted text> 
                \par 
l.3768 ...Impute}}\label{imputation-pipeopimpute}}

Error: Failed to compile mlr3book.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See mlr3book.log for more info.
In addition: There were 14 warnings (use warnings() to see them)
Execution halted
make: *** [Makefile:29: pdf] Error 1
edd@rob:~/git/mlr3book(master)$ 
```

with

```
(Font)              scaled to size 8.00085pt on input line 3768.
LaTeX Font Info:    Font shape `TU/latinmodern-math.otf(3)/m/n' will be
(Font)              scaled to size 11.99872pt on input line 3768.
LaTeX Font Info:    Font shape `TU/latinmodern-math.otf(3)/m/n' will be
(Font)              scaled to size 7.99915pt on input line 3768.
! Argument of \@sect has an extra }.
<inserted text> 
                \par 
l.3768 ...Impute}}\label{imputation-pipeopimpute}}
                                                   
Here is how much of TeX's memory you used:
 33949 strings out of 494862
 621471 string characters out of 6175651
 1000110 words of memory out of 5000000
 37450 multiletter control sequences out of 15000+600000
 543804 words of font info for 126 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 60i,9n,118p,9107b,601s stack positions out of 5000i,500n,10000p,200000b,80000s

Output written on mlr3book.pdf (129 pages).

edd@rob:~/git/mlr3book(master)$ tail -20 bookdown/mlr3book.log 
```

Happy to run any diagnostics.  I poked around a little to no avail last evening and didn't manage to fix it.

*Edit:* Accidentally had a `make html` log at first, now showing `make pdf`.  The actual TeX logfile was accurate.

**Comment by eddelbuettel** [comment]
And `~/bin/pandoc` points to the one from RStudio, now 2.7.3.  The distro gives me 2.5.

**Comment by pat-s** [comment]
I experienced this a while ago already but it is/was low prio lately. We need to put some time into that to make it robust and also visually applicable. 

Thanks for the report!

**Comment by eddelbuettel** [comment]
Well as you know I put a few mini-PRs in so it worked just fine and reliably for me on Ubuntu.  I didn't have a chance to run for maybe two or three weeks during which I also upgraded from 19.04 to 19.10.  So either the possibly-slightly-newer texlive bites, or you good folks made changes.

**Comment by pat-s** [comment]
We didn't made any pdf specific changes and AFAICS only some wording updates to the whole book. So its more likely that one of the other points are responsible for it.

Maybe I can find some time during christmas to sort it out.

**Comment by eddelbuettel** [comment]
Thanks for looking into it.  Let me know if I can help.

I too am writing a metric ton with rmarkdown for pdf (or html, at time) but I am surprised how fragile your setup is.  I turned the Rcpp Gallery into a (unreleased) rmarkdown manuscript of 300+ pages and it seems less finicky.  (Then again I am not trying to do html and pdf at the same time, which is surely harder to pull off.)

**Comment by mllg** [comment]
Turns out that you cannot have hyperlinks in headings for pdf output. I've fixed this and did some other cleanups. I now can build locally again.

I'll try to merge the open PRs ASAP and then proceed and set up a CI job for the PDF.

**Comment by eddelbuettel** [comment]
This did get fixed in master so I think we can close this now.
