### ISSUE TITLE
Fix texlive installation

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3book#112]
Tinytex is not working (missing package `unicode-math`, required for `xelatex`, and `tlmgr` is not working properly). This could be a temporary problem, I haven't found any bug reports. 

Either switch back to tinytex, switch back to xelatex or switch to circle-ci.

**Comment by mllg** [comment]
Update: Same issue with texlive.

**Comment by pat-s** [comment]
Maybe https://github.com/mlr-org/mlr3book/blob/fb326bc740267db82a54411affec95e4de9cc052/.travis.yml#L9-L27 does the job.

**Comment by eddelbuettel** [comment]
My Ubuntu 19.10 box has it in `texlive-latex-recommended.

```
edd@rob:~$ dpkg -S /usr/share/texlive/texmf-dist/tex/latex/unicode-math
texlive-latex-recommended: /usr/share/texlive/texmf-dist/tex/latex/unicode-math
edd@rob:~$ 
```

Package names change though.  I had good luck switch "complicated" / "larger dependency set" Travis jobs to custom Docker images....

**Comment by mllg** [comment]
Works now (forgot to set `latex: false` explicitly). And yes, I also want to have a custom docker image in the long run. I already did a test run some month ago and everything looked promising. I just wasn't sure if I should build on a rocker image or go with Arch so that I know what I'm doing.

**Comment by eddelbuettel** [comment]
Re Docker:  I happen to like rocker/r-base as it already has R plus access to Debian testing. I also made a latex-heavy container [r-rmd](https://github.com/rocker-org/rocker/blob/master/r-rmd/Dockerfile) to test my RMarkdown (wrapper) packages and that should already contain most of what you need.  But as always there is appeal to starting from scratch and controlling all bits and pieces --- your call.  Happy to help from the Rocker side if you have questions.

**Comment by pat-s** [comment]
We are using `rocker:verse` successfully since a few months in {mlr}

https://github.com/mlr-org/mlr/blob/3d7e0aa91936e82cf108aff3c46b19e3f953eefd/.circleci/config.yml#L6-L7

Michel and I are still in discussion whether to use this image (which also comes with LaTeX supp) or to create a new one just for mlr3 pkgs.

**Comment by eddelbuettel** [comment]
Very well, but note that is indeed a different "stack" within Rocker as it starts from versioned snapshots (ie r-ver, Carl's preference). For what I do with often somewhat narrower images I prefer to start from Debian rolling releases using Rocker r-base.  

At the end of the day both get you to a working state.

**Comment by pat-s** [comment]
Thanks.

The big advantage is the versioning + LaTeX supp here which lets you easily test on multiple R versions.

Rather than numeric versions slugs I'd also like to have character indicators such as `rocker/verse:r-release` to stay dynamic on R-version updates. But that is a different things.

Ok, we slightly go off-topic here. Happy to discuss this in a new separate issue :)

**Comment by eddelbuettel** [comment]
Patrick, I added essentially one-line as a note to Michel, and you then hijacked the thread.  Re your claim of multiple versions: we have version tags for r-base that do that too if one desires.   No need to follow-up further; we know where to find each other online.

**Comment by pat-s** [comment]
> Patrick, I added essentially one-line as a note to Michel, and you then hijacked the thread. 

I know, this was no fingerpointing at you. Just a plain statement of the situation.

**Comment by eddelbuettel** [comment]
Which, sadly, still needed further clarifcations.
