### ISSUE TITLE
Tutorial request: threshold tuning 

### ISSUE THREAD

**Issue by missuse** [mlr-org/mlr3book#117]
Hi again,

threshold tuning is a very important part of binary classification workflows yet in the book it is on the "yet to be added list". I haven't found anything regarding this in the documentation either. Could you post a brief example on how to perform it in mlr3?

Thanks,

Milan

unrelated EDIT1: I am thrilled with database backends. It was much needed.
unrelated EDIT2: Not so thrilled with the fact parallelization levels can not be chosen as in mlr. In my opinion this offered some nice benefits, especially when using some sort of guided hyper parameter search with nested re-sampling.

**Comment by pat-s** [comment]
> Not so thrilled with the fact parallelization levels can not be chosen as in mlr. In my opinion this offered some nice benefits, especially when using some sort of guided hyper parameter search with nested re-sampling.

By default all levels are now parallelized which we see as an improvement. If there is something you do not like/miss, please open a separate issue in {mlr3} (which describes the problem in more detail).
Thanks for the feedback!

**Comment by mllg** [comment]
Can be tackled as soon as https://github.com/mlr-org/mlr3pipelines/pull/356 hits CRAN.

**Comment by pfistfl** [comment]
Solved here: https://mlr3gallery.mlr-org.com/posts/2020-10-14-threshold-tuning/
