### ISSUE TITLE
How to set a cost parameter for SVM learner? 

### ISSUE THREAD

**Issue by kotamine** [mlr-org/mlr3book#118]
Hi I am new to mlr3 and am trying to tune svm for cost parameter.  Before using AutoTuner, I try to set the cost parameter at a fixed level, but I don't understand the error message. 

When I try: 
lrn_svm =  lrn("classif.svm", cost=10)

I get an error message:
Error in (function (xs)  : 
  Assertion on 'xs' failed: Condition for 'cost' not ok: type equal C-classification; instead: type=<not-there>. 

Could you help me with this?

**Comment by pat-s** [comment]
See https://stackoverflow.com/questions/59653077/error-on-tuning-parameters-using-classif-svm-in-mlr3

Please use Stackoverflow for usage questions in the future, not this repo. Thanks!

**Comment by berndbischl** [comment]
also see this issue, here, 
https://github.com/mlr-org/paradox/issues/259

we will make this a bit more transparent what to do in the packge, but for now simply use my fix from there

learner = lrn("classif.svm")
learner$param_set$values = list(type = "C-classification", cost = 1)
or 
learner = lrn("classif.svm", type = "C-classification", cost = 1)

**Comment by berndbischl** [comment]
> Please use Stackoverflow for usage questions in the future, not this repo. Thanks!

for reference, i do think this is a 50% bug / useabilty problem, so opening an issue was not really incorrect.... 
its just that we already HAVE the issue in paradox ;-)
