### ISSUE TITLE
Structure: Group extension in their own chapter

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3book#12]
Rather than having top-level chapter for extension like "Survival" and friends, I suggest to group them under a heading called "mlr3 Extensions".
Candidates are:

- Survival
- Forecasting
- Spatial
- Costsens
- Ordinal

This keeps the structure clean and aligns with the "Extension" principle of the packages.

@mllg

**Comment by berndbischl** [comment]
Not sure I agree here. But at some point, not now, we might structure the book into names parts.

Extensions is pretty general and generic...

**Comment by pat-s** [comment]
No need to agree :)

"Names parts"? What do you mean exactly?

And yes, "extensions" might be a bit too general.

**Comment by berndbischl** [comment]
Sorry typo. I meant "named parts". Like this.

Part 1. Core functionality
Chap1 mlr3
Chap2 paradox 
Part2. Efficient pipelines
Chap3. Intro to mlr3lipelines
Chap4. Optimize pipelines
Part3. Blaa

So like this chapters are still on top level but nicely separated

**Comment by pat-s** [comment]
We re-organized the structure and this issue does not apply anymore. "Extensions" are now listed under "Special Tasks".

**Comment by berndbischl** [comment]
Extensions should be under extensions... M

**Comment by pat-s** [comment]
Then let's say that my naming of "extensions" was meant to be the "special tasks". :)
