### ISSUE TITLE
Train/Test set specification method

### ISSUE THREAD

**Issue by ChuanTC** [mlr-org/mlr3book#123]
Hi mlr3 team,

I am new to the `mlr3` package and I try to follow the online guideline book and learn. I find that the book indicates using `sample()` and `setdiff()` to generate training and test sets ([https://mlr3book.mlr-org.com/train-predict.html](url)). I am wondering if the team considers to include a more advanced method to generate train/test sets based on the ratio of target, something similar to the `createDataPartition()` function in the `caret` package? I believe it would be useful for many ML applications. Many thanks. 

Chuan

**Comment by jakob-r** [comment]
Damit, wrong issue number... Fixed here: https://github.com/mlr-org/mlr3book/commit/baf957d06dfc77be08a6b8cd4c39ccb76270edd6
