### ISSUE TITLE
describe column roles more clearly

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#128]
The description of column roles is not sufficient when I first encounter it in 2.2 Tasks. There are a few lines of code showing how to change the role (although it's not clear to me at first read which of the last two of the following lines actually makes the change):
```
task$feature_names
## [1] "cyl"  "disp" "rn"

# working with a list of column vectors
task$col_roles$name = "rn"
task$col_roles$feature = setdiff(task$col_roles$feature, "rn")
```

And it appears, upon closer examination, that there is quite a number of  different roles that columns can have. Maybe this is explained in more detail somewhere else and a link could be provided here? E.g. I found lots of other potential roles, it appears:
```
> task$col_roles
$feature
[1] "cyl"  "disp" "rn"  

$target
[1] "mpg"

$name
character(0)

$order
character(0)

$stratum
character(0)

$group
character(0)

$weight
character(0)
```

**Comment by mllg** [comment]
Is https://github.com/mlr-org/mlr3book/commit/fa16668b58e392c2f0d46dc77229dc8a6b7ee452 enough to solve this?

**Comment by nickreich** [comment]
I added a minor comment on the commit. Basically looks good.

**Comment by mllg** [comment]
Updated on master with your suggestion.
