### ISSUE TITLE
add more details about resampling strategies

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#130]
I suggest adding, in section 2.5.1 not just the dictionary lookup of `mlr_resamplings` as is currently there, but also the full output of
```
> as.data.table(mlr_resamplings)
           key        params iters
1:   bootstrap repeats,ratio    30
2:      custom                   0
3:          cv         folds    10
4:     holdout         ratio     1
5: repeated_cv repeats,folds   100
6: subsampling repeats,ratio    30
```
as this provides quite a bit of more useful info to the reader. I ended up digging around for a few minutes and running this command myself and then the lightbulb went off. It's also helpful for me to have the underlying structures here reinforced, and the idea that each of these things can be accessed separately.

**Comment by pat-s** [comment]
Thanks!
