### ISSUE TITLE
fix unclear sentence about resampling with multiple learners

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#131]
The following sentences are in 2.5.3:
> Note that if you want to compare multiple [learners](#learners), you should ensure to that each learner operates on the same resampling instance by manually instantiating beforehand.
This reduces the variance of the performance estimation.

The first sentence is not grammatically correct ("...ensure to that..." is not right) but I wasn't sure how to fix it because I wasn't actually sure what this is saying. Can it be rephrased and made clearer?

**Comment by pat-s** [comment]
Thanks Nick. Could you add a direct link to the section you are referring to in future issues? Thanks!

**Comment by nickreich** [comment]
will do.
