### ISSUE TITLE
add detail in description of autoplot.ResampleResult()

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#132]
Section 2.5.5: I recommend adding at least one sentence about each of the figures, just describing what the plot is, even if it seems obvious. In particular, for the ROC curve, I think it's important to describe what the shaded ribbon represents. Is it a range across all resampling iterations? Some estimate of a 5th/95th percentile?

Also, when I visit the linked documentation page https://mlr3viz.mlr-org.com/reference/autoplot.ResampleResult.html
there are quite a few more plots of different kinds that also look interesting and could perhaps be shown here.

**Comment by RaphaelS1** [comment]
Added to https://github.com/mlr-org/mlr3book/issues/439
