### ISSUE TITLE
Extensions: Adding a custom Tuner - code fails

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3book#14]
Currently working with chunk option `error = TRUE`.
Probably the API changed since this section was created by @schalkdaniel.

@schalkdaniel 	Could you take a look and fix this? 
I assume it would be a quick one for you.

**Comment by pfistfl** [comment]
I guess this is intended?

The text below says: 
```
Oh! The error message tells us that we need to specify an addition argument called `terminator`.

**Comment by pfistfl** [comment]
I guess this is intended?

The text below says: 
```
Oh! The error message tells us that we need to specify an addition argument called `terminator`.
```

**Comment by mllg** [comment]
This is probably the section we need last. Additionally, we might refactor the tuning package anyways. Can we move this section into attic for now?

**Comment by pat-s** [comment]
Let me push my changes later on and then I'll move it to attic.

**Comment by pat-s** [comment]
Invalid meanwhile.

We might want to add a section about how to add a custom tuner at some point - but this is very niche.
