### ISSUE TITLE
create a proper title page for the book

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#143]
I suggest creating a more proper title/intro page for the book. Right now when you load the index page for the book, it shows you the quickstart. But there is nothing that provides a first-time reader with more general quickly digested overview information. I suggest adding things like:
 - the name of the package
 - 1-2 sentences about basic functionality/aims/goals
 - a link to the quickstart for those who don't want the overview :-)
 - maybe that nice mlr3verse image?
 - maybe a list of authors or a team name, with a link to a site with more information about who is creating this
 - information about versioning and/or licensing of the mlr3 package itself and content within the book.
 - Links to other resources, e.g. the CRAN mlr3 site, other mlr3 sites, mlr3 github site, mlr3book github site, etc...

I think the Stan reference manual has a nice front page that captures some of this.
https://mc-stan.org/docs/2_22/reference-manual/index.html

If you all think this is a good idea, I could take a pass at trying to draft this.

**Comment by pat-s** [comment]
@nickreich Are you still interested in drafting a title page?

**Comment by nickreich** [comment]
Interested yes, but no time anymore due to corona modeling commitments in the US.

**Comment by RaphaelS1** [comment]
Closing as this will become title page of the published book
