### ISSUE TITLE
text overlap in tuning figure

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#144]
At the very top of this page:
https://mlr3book.mlr-org.com/tuning.html

![image](https://user-images.githubusercontent.com/1280767/74147620-e2afb400-4c03-11ea-9290-749a2e14d36c.png)

**Comment by jakob-r** [comment]
This is already fixed.

**Comment by nickreich** [comment]
Sorry, hadn't reloaded the book in a while. :-)

**Comment by jakob-r** [comment]
No problem :) I just fixed it some hours ago and then it needed some time until it got deployed ;)
