### ISSUE TITLE
Introduction to the tuning section could provide additional clarity

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#145]
I suggest starting the Hyperparameter Tuning section (https://mlr3book.mlr-org.com/tuning.html) with a few sentence overview of the process and goal of hyperparameter tuning. I considered adding this directly to my next PR, but I'm leaving to PRs for things that I think are more cut-and-dry and may not require such detailed editorial input, such as grammatical/spelling/language corrections.

For this, I might suggest something like the follwing:
"Hyperparameters are second-order parameters of machine learning models that, while often not explicitly optimized during the model estimation process, can have important impacts on the outcome and predictive performance of a model. Typically, hyperparameters are fixed before running a model. However, because the output of a model can be sensitive to the specification of hyperparameters, it is often recommended to make an informed decision about which hyperparameters may yield better model performance. In many cases, hyperparameters may be chosen a priori, but it can be advantageous to try different sets of hyperparameters before fitting your model on the training data. This process is often called 'tuning' your model."

**Comment by jakob-r** [comment]
Again, thanks for the input!
We kind of have a similar text [in the introduction of the model optimization chapter](https://mlr3book.mlr-org.com/model-optim.html) but I guess yours is better. 
I think an isolated PR for such a paragraph would be perfect. This would also make sure that your contribution is always counted.

I know... it will probably end up in a lot of little PRs and branches with your great contributions. If this is not too much of hassle on your side it would help us tremendously to merge things quickly.

**Comment by nickreich** [comment]
Ok, will submit as a separate PR. :-) thanks!
