### ISSUE TITLE
print(result) returning NULL

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#148]
I'm not sure what this line is supposed to be adding or showing, but right now it is printing null

https://github.com/mlr-org/mlr3book/blob/d9a4fcd9414d5e1d15a9e4ca921f6339c82ee53e/bookdown/03-optimization.Rmd#L164

![image](https://user-images.githubusercontent.com/1280767/74158126-cdde1b00-4c19-11ea-8308-ab5b68a129da.png)

**Comment by mllg** [comment]
`Tuner$tune()` returned `NULL`. Now returns `self` (https://github.com/mlr-org/mlr3tuning/commit/6bddf3965a7b64e76d91b9fc5bef25d1eb76f907), so this should be fixed after the next CRAN upload.
