### ISSUE TITLE
Add clarification to filtering sections

### ISSUE THREAD

**Issue by nickreich** [mlr-org/mlr3book#149]
https://mlr3book.mlr-org.com/fs.html#fs-calc

I suggest adding a bit more detail to this section to make it easier to follow and understand. 
 - in the example, explain what JMIM/CMIM means for the uninitiated. 
 - explain what the column of "scores" represent.
 - right now, these scores are shown, but an example is not given of how they might be used to actually do feature selection. Could this be illustrated as well with a simple example? 
 - explain in more details what the `param_set` of the filters are and what they mean.
 - it's not clear to me how the different methods of specifying `FilterJMIM$new()` vs. `flt("jmim")` are similar or different. can this be explained?

I guess this seems like a section that is still undergoing some changes, but compared to much of the other content, this felt a bit sparse.

**Comment by mllg** [comment]
@pat-s can you have a look?

**Comment by RaphaelS1** [comment]
Closed/NA in new version
