### ISSUE TITLE
Blocks not working in HTML

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3book#154]
They sometimes just are located under the navbar, sometimes come without logo, and generally do not execute contained code.

![image](https://user-images.githubusercontent.com/1260920/74327857-326db700-4d8d-11ea-959b-34f3ec05a2ce.png)

**Comment by mllg** [comment]
I guess I'll just remove them, they are rarely used.

**Comment by jakob-r** [comment]
Would have been an easy CSS fix - if you ever want to reintroduce them :)
