### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by HeidiSeibold** [mlr-org/mlr3book#161]
I received this from one of the students. They are carefully reading the book :wink: 

> ich wollte euch nur kurz informieren, dass auf der Seite „2.1 Quick R6 Intro for Beginners“ (https://mlr3book.mlr-org.com/r6.html) noch ein kleiner Rechtschreib- bzw. Grammatikfehler ist.
> 
> R6 variables are references to objects rather then the actual objects, which are stored in an environment.
> 
> In diesem Zusammenhang müsste es „than“ nicht „then“ heißen, oder?

**Comment by berndbischl** [comment]
we happily receive these issues, keep them coming. 
but at least CONSIDER for these clear typo cases to directly do PR...
