### ISSUE TITLE
LOO CV resampling absent from mlr_resamplings

### ISSUE THREAD

**Issue by wzel** [mlr-org/mlr3book#176]
`bookdown/02-basics-resampling.Rmd` says:

> predefined resampling strategies: Cross-validation, Leave-one-out cross validation, Repeated cross-validation, Out-of-bag bootstrap and other variants (e.g. b632), Monte-Carlo cross-validation and Holdout.

, but `mlr_resamplings` does not seem to list Leave-one-out cross validation resampling for `mlr3`, at least not explicitly, as it is defined in the `mlr` package. I checked every strategy, suspecting that maybe it was hidden under another name, but none appears to match LOO for me. Is this an error in the book or am I missing something?

I can imagine LOO being a special case of a more general strategy (like an n-fold CV with the number of folds equal to the number of data points). If this is how it should be performed in `mlr3`, IMHO this needs to be given a separate note in the book.

**Comment by mllg** [comment]
I guess this sentenced was copied from the mlr(2) docs. I've added LOO to mlr3 and will fix this sentence.

Thanks for reporting.
