### ISSUE TITLE
Chapter on measures missing

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr3book#236]
We have:
- list of measures
- how to implement own measure

But not how to work with existing measures. This chapter could show how to 
- calc. measures after train/test
- for vectors
- how to change aggregations
- etc.

**Comment by RaphaelS1** [comment]
Also relevant https://github.com/mlr-org/mlr3book/issues/246

**Comment by RaphaelS1** [comment]
Now in 2.2
