### ISSUE TITLE
`make install` succeeds even when package installations fail

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr3book#263]
Running `make install` to install all dependencies seems to always succeed, even if the installation of some packages doesn't. This can be hard to tell as the output is buried in pages and pages of other output. Is there a way to have `make install` fail if and when a package isn't installed correctly?

**Comment by RaphaelS1** [comment]
@larskotthoff is this still relevant?

**Comment by larskotthoff** [comment]
I believe so.

**Comment by RaphaelS1** [comment]
Okay, and who can fix this?

**Comment by larskotthoff** [comment]
Well... not sure. Part of the problem is that running `make install` takes a long time, so it's not easy to debug. It might be as easy as calling `Rscript` multiple times instead of once with multiple `-e` arguments though.

**Comment by RaphaelS1** [comment]
Closing - seen this from my side and doesn't seem to impact book build or content
