### ISSUE TITLE
doc package options on cheatsheet / book

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3book#264]
from package man page

"mlr3.debug": If set to TRUE, parallelization via future is disabled to simplify debugging and provide more concise tracebacks. Note that results computed with debug mode enabled use a different seeding mechanism and are not reproducible.

"mlr3.allow_utf8_names": If set to TRUE, checks on the feature names are relaxed, allowing non-ascii characters in column names. This is an experimental and temporal option t

also check for other stuff

**Comment by RaphaelS1** [comment]
Do we still have/use these options @berndbischl @mllg ?

**Comment by mllg** [comment]
These two options are still in use. I can add a note to the parallelization chapter.

**Comment by RaphaelS1** [comment]
Thanks! Would you mind adding a similar short note to basics maybe (or whether you yhink best) for the second?

**Comment by mllg** [comment]
Yep, I will add this to PR #501.
