### ISSUE TITLE
Compiling of book fails on chapter 9 with pdf, html, and serve method

### ISSUE THREAD

**Issue by nfoss2** [mlr-org/mlr3book#265]
I followed the installation instructions and when I tried to compile the book I get this error message:
<img width="546" alt="Screen Shot 2021-10-29 at 11 14 09 AM" src="https://user-images.githubusercontent.com/55253059/139476034-aee5117b-c8d7-4ca6-a688-a1302a1f6ce9.png">
This same message occurs when I try to compile to a pdf, html or the serve command. 
I have also tried all three of these through the makefile (make pdf, make html, and make serve) with the same result.

**Comment by nfoss2** [comment]
I am running R version 4.1.1 (2021-08-10)
and 1.14.3 for data.table

**Comment by pat-s** [comment]
Our CI builds bot HTML and PDF every day. If the build is green, everything is fine (which applies currently).

You can see which package versions were used in the [DESCRIPTION](https://github.com/mlr-org/mlr3book/blob/main/DESCRIPTION).  Unless notes, only CRAN versions are used.

The easiest take would be update all your packages, ensure they can be loaded, and try again :)

**Comment by mllg** [comment]
Assuming this fixed itself after an update, re-open if this is not the case.
