### ISSUE TITLE
Text doesn't follow the code ?

### ISSUE THREAD

**Issue by MislavSag** [mlr-org/mlr3book#268]
I chapter 4.3.1 Execution, you wrote:

> We use a 4-fold cross-validation in the inner resampling loop. The AutoTuner executes the hyperparameter tuning and is stopped after 5 evaluations. The hyperparameter configurations are proposed by grid search.

Then, there is an code:
```
library("mlr3verse")

learner = lrn("classif.rpart")
resampling = rsmp("holdout")
measure = msr("classif.ce")
search_space = ps(cp = p_dbl(lower = 0.001, upper = 0.1))
terminator = trm("evals", n_evals = 5)
tuner = tnr("grid_search", resolution = 10)

at = AutoTuner$new(learner, resampling, measure, terminator, tuner, search_space)
```
Doesn't that mean the inner resampling is holdout and not 4-fold CV ?

**Comment by larskotthoff** [comment]
Thanks, well spotted. I've updated the code.
