### ISSUE TITLE
Possible predict types for Survival Learner

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#274]
In section 8.1.2 it says that every PredictionSurv object can predict one or more of lp, distr and crank. 
However I think this is incorrect because e.g. The Survival SVM from mlr3extralearners can predict "response". 
@RaphaelS1 can I correct this?

**Comment by RaphaelS1** [comment]
Good spot! Yes please!

**Comment by RaphaelS1** [comment]
@sebffischer has this been done?

**Comment by RaphaelS1** [comment]
Added here https://github.com/mlr-org/mlr3book/issues/441

**Comment by sebffischer** [comment]
Sorry for the late response, I think I already added that.
