### ISSUE TITLE
Pipelines "backuplearner"

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#281]
The pipelines chapter mentions the PipeOp "backuplearner" but it does not exist in DictionaryPipeOp

```
> po("backuplearner")
Error: Element with key 'backuplearner' not found in DictionaryPipeOp!
```

**Comment by sebffischer** [comment]
@mb706

**Comment by RaphaelS1** [comment]
Where are we with this @mb706 @sebffischer ? Code currently commented out in the book. Should either be removed or fixed in pipelines

**Comment by mb706** [comment]
It is there to make a point about pipeops with different input / output types. This can be replaced with another pipeop that has varying output types (back then we didn't have any of those)

**Comment by RaphaelS1** [comment]
Great would you mind picking another then? Throughout the book we should remove all examples that are commented out because they don't currently work!
