### ISSUE TITLE
How to manually setup different prediction time?

### ISSUE THREAD

**Issue by yuanyuan102** [mlr-org/mlr3book#288]
Hi!

In the section 8.1.2, I saw we could do prediction by: prediction = learn$predict(task, row_ids = test_set) line, and got
##         298   92  FALSE -1.7918 -1.7918 <list[1]>

But I wonder:
1. what "time" value does the algorithm use to calculate the lp value? for example, for id9, is the lp=-0.3578 predicted at time 104?
2. can we provide a vector of time value, so we could predict lp/crank for a subject at different time points? for example, in the “pec” package, there is a “predictSurvProb” function, in which we could define a vector of times to return the corresponding survival probabilities vector. (https://www.rdocumentation.org/packages/riskRegression/versions/2019.01.29/topics/predictSurv)
3. if we could specify different time points for each subject, how could we do that?
Thanks in advance!

**Comment by pat-s** [comment]
Please ask such questions on Stackoverflow and put some time into formatting your question and code, thanks!
