### ISSUE TITLE
Autofselector models (e.g. surv.aft and sruv.cox) Don't Work Inside Benchmarks 

### ISSUE THREAD

**Issue by aalhadab** [mlr-org/mlr3book#291]
When I used an autofselector$new model inside benchmark() does not work and I get the following error 

Error: Output type of PipeOp select during training (Task) incompatible with input type of PipeOp impute median.impute mode.scale.encode.surv.coxph (Task Surv)" 

See example (https://stackoverflow.com/q/71261616/17537724)

**Comment by larskotthoff** [comment]
Please don't cross-post, in particular not in a repository that has nothing to do with your problem.
