### ISSUE TITLE
Update `row_roles` name

### ISSUE THREAD

**Issue by bblodfon** [mlr-org/mlr3book#310]
Hi,

I am reading throught the book and noticed this:
```
actg_task = tsk('actg')
names(actg_task$row_roles)
[1] "use"     "holdout"
```
[Here](https://github.com/mlr-org/mlr3book/blob/main/bookdown/02-basics-tasks.Rmd#L250) the 2nd role name is `validation`, so maybe it was updated in the code but not in the doc?

**Comment by mllg** [comment]
Docs have updated, thanks for reporting.
