### ISSUE TITLE
`custom_cv` resampling is not listed 

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3book#399]
in https://mlr3book.mlr-org.com/performance.html#sec-resampling

It is listed in the dictionary further down though: https://mlr3book.mlr-org.com/performance.html#resampling-settings

A short description would also be nice to have.

**Comment by RaphaelS1** [comment]
Added to Chapter 3 comments issue  https://github.com/mlr-org/mlr3book/issues/440
