### ISSUE TITLE
Typos 

### ISSUE THREAD

**Issue by ge-li** [mlr-org/mlr3book#402]
https://github.com/mlr-org/mlr3book/blob/74820a58e18747dd1826c9781764b5c85b89b8e1/book/intro.qmd#L45

~~unnecassary~~ -> unnecessary

**Comment by ge-li** [comment]
https://github.com/mlr-org/mlr3book/blob/74820a58e18747dd1826c9781764b5c85b89b8e1/book/basics.qmd#L291

~~have have~~ -> have

**Comment by jemus42** [comment]
Thanks! Fixes will be merged soon.
