### ISSUE TITLE
Replace assignment operator

### ISSUE THREAD

**Issue by DiegoChillon** [mlr-org/mlr3book#403]
I have noticed that throughout the book the assignment operator used is `=` rather than the recommended `<-` for R (see this [section](https://style.tidyverse.org/syntax.html#assignment-1) of the [Tidyverse](https://www.tidyverse.org/) style guide). I would suggest the replacement of all instances to improve code readability and stick with the Tidyverse syntax.

Kind regards.

**Comment by jemus42** [comment]
mlr3 is not part of or related to the tidyverse and adheres to its own [style guide](https://github.com/mlr-org/mlr3/wiki/Style-Guide).

I can't speak to whether or not this style guide may change in the future, or whether or not there may be an exception to the rule for the book to make it more approachable — but if the book used a different style, there would be an inconsistency between the book about mlr3 and mlr3 itself, so it's not a straight forward decision and also not something we could easily change with a search+replace.
