### ISSUE TITLE
Add introductory section

### ISSUE THREAD

**Issue by jemus42** [mlr-org/mlr3book#407]
As a replacement for the Quickstart section, since the book website needs some kind of "landing page" and quarto requires an `index.qmd` to exist.

Some sort of foreword or acknowledgements were ideas that came up.

**Comment by pat-s** [comment]
While a rewrite of the intro can always be done, I don't understand why the current quickstart was removed in favor of a placeholder? 3b1e6f74a873f4546ff568c3ddd0bfe931424c89

The current version looks odd and worse than before. Can we revert and wait for a proper PR to update the section?

**Comment by RaphaelS1** [comment]
I wouldn't stress about this now. We can have Title Page -> Preamble -> Introduction. The quickstart will become the preamble in the printed version and the title page will be based on the book, e.g. using [this](https://r4ds.had.co.nz/) as an example. If you both agree I'll close this for now.

**Comment by larskotthoff** [comment]
Do we still want this for the printed book? Not sure if it makes much sense there. But definitely need a quickstart for the online version.

**Comment by RaphaelS1** [comment]
The printed book will definitely need a preamble as well as installation instructions. Once that's made we could then take something shorter for quickstart, but tbh this could end up being same as mlr3 readme
