### ISSUE TITLE
downlit doesn't seem to recognise mlr3 functions in some chapters

### ISSUE THREAD

**Issue by jemus42** [mlr-org/mlr3book#410]
In a code chunk like 

```r
task = tsk("sonar")
learner = lrn("classif.rpart", predict_type = "prob")

# split into training and test
splits = partition(task, ratio = 0.8)
print(str(splits))
```

base R functions like `print` and `str` are correctly linked, but `lrn`, `tsk` and `partition` are not.  
Unfortunately I don't know if downlit is configurable in some way or what we can do to nudge it in the right direction.
The documentation [lists requirements](https://downlit.r-lib.org/#cross-package-links), but the [mlr3 `DESCRIPTION`](https://github.com/mlr-org/mlr3/blob/main/DESCRIPTION#L57) has the correct links and [`_pkgdown.yml`](https://github.com/mlr-org/mlr3/blob/main/pkgdown/_pkgdown.yml#L1) appears to be correctly set up as well.

EDIT:
This affects the [performance chapter](https://mlr3book.mlr-org.com/performance.html), but oddly enough not the [optimisation chapter](https://mlr3book.mlr-org.com/optimization.html#tuning-optimization).

The main difference appears to be that in the optimisation chapter there's a `library(mlr3verse)` call in a code chunk. Doing the same in the performance chapter fixes the issue, but that chapter is undergoing a rewrite anyway.

Adding `library(mlr3verse)` to `_setup.qmd` doesn't help, so I guess we'll have to make sure to load `mlr3verse` at the beginning of a chapter.

**Comment by pat-s** [comment]
I also came across that when (lazy) caching is used, namespaces are not fully populated. With a loaded NS, {downlit} won't work correctly AFAICS. 

One solution could be to add an `echo=FALSE` chunk to every section file which loads the respective namespaces upfront. Do you want to check this out eventually an open a PR?
