### ISSUE TITLE
Deploy branches / PRs for previewing via netlify

### ISSUE THREAD

**Issue by jemus42** [mlr-org/mlr3book#411]
For branches that include either larger chapter rewrites or e.g. changes to the quarto setup etc., it would be nice to have a dedicated rendered version to preview changes (and more quickly gather feedback).

I'm aware of workflows to r.g. render [pkgdown sites for branches](https://github.com/r-lib/pkgdown/blob/main/.github/workflows/pkgdown.yaml#L59-L74) and deploy to netlify, and suspect I could figure out how to set up something like this.

@pat-s, I've been told you're the one to talk to about that 😁

**Comment by pat-s** [comment]
Yes, Netlify previews are possible! Currently the mlr-org account on Netlify runs on me and access is unfortunately restricted to three people due to Netlify's free plan policy but I can see if I can get something going soon.

**Comment by jemus42** [comment]
PRs now have their own previews, so this is done I guess
