### ISSUE TITLE
Auto-generate tables for dictionaries

### ISSUE THREAD

**Issue by jemus42** [mlr-org/mlr3book#413]
Example would be table of resamplings in [the performance chapter](https://mlr3book.mlr-org.com/performance.html#sec-resampling), which is currently manually created.
This is both tedious and prone to error, see e.g. the omission of `custom_cv` (#399).

For cases like this I'd like to auto-generate tables from dictionaries with auto-linked help pages, and I came up with something along those lines (which could of course be improved/generalized, but the idea is straight forward):
``` r
library(mlr3)
resampling_dt <- as.data.table(mlr_resamplings)[, c("label", "key")]
resampling_dt$key <- vapply(resampling_dt$key, function(x) {
  mlr3book::ref(topic = paste0("mlr_resamplings_", x), text = sprintf("\"%s\"", x))
}, character(1))

knitr::kable(
  resampling_dt, escape = FALSE,
  col.names = c("Name", "Identifier"),
  caption = "Resampling strategies included in mlr3"
)
```

| Name                          | Identifier                                                                             |
|:------------------------------|:---------------------------------------------------------------------------------------|
| Bootstrap                     | [`"bootstrap"`](https://mlr3.mlr-org.com/reference/mlr_resamplings_bootstrap.html)     |
| Custom Splits                 | [`"custom"`](https://mlr3.mlr-org.com/reference/mlr_resamplings_custom.html)           |
| Custom Split Cross-Validation | [`"custom_cv"`](https://mlr3.mlr-org.com/reference/mlr_resamplings_custom_cv.html)     |
| Cross-Validation              | [`"cv"`](https://mlr3.mlr-org.com/reference/mlr_resamplings_cv.html)                   |
| Holdout                       | [`"holdout"`](https://mlr3.mlr-org.com/reference/mlr_resamplings_holdout.html)         |
| Insample Resampling           | [`"insample"`](https://mlr3.mlr-org.com/reference/mlr_resamplings_insample.html)       |
| Leave-One-Out                 | [`"loo"`](https://mlr3.mlr-org.com/reference/mlr_resamplings_loo.html)                 |
| Repeated Cross-Validation     | [`"repeated_cv"`](https://mlr3.mlr-org.com/reference/mlr_resamplings_repeated_cv.html) |
| Subsampling                   | [`"subsampling"`](https://mlr3.mlr-org.com/reference/mlr_resamplings_subsampling.html) |

Resampling strategies included in mlr3

<sup>Created on 2022-09-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by pat-s** [comment]
We already do so in the [mlr3website](https://github.com/mlr-org/mlr3website/blob/main/mlr-org/resamplings.Rmd). You could copy the logic from there.

**Comment by RaphaelS1** [comment]
I don't think we should necessarily do this. The tables we currently have already don't provide enough info to be valuable to the user, in your example it would be useful to add a column that very briefly explains each method.

**Comment by jemus42** [comment]
I guess it makes sense in the HTML context where it's a clickable link to the docs, as a "further reading" - but I see how in the printed/offline-PDF context it's not necessarily valuable.

Depends on whether the "overview of things available via <insert dictionary here>" is considered useful/suitable for the (printed) book or if it should always be a link to up-to-date docs/website anyway.

**Comment by RaphaelS1** [comment]
General issue unfortunately. Agreed for online we want it to always be up-to-date but of course this isn't possible for the book. My preference is to pick consistency based on the book and accept this is sub-optimal (happy to be convinced otherwise).

**Comment by larskotthoff** [comment]
Could be appendices that are not included in the print version? I also agree that we want this online, but I don't think it would add much value for the book.

**Comment by RaphaelS1** [comment]
Or we could do something similar to the [learner search](https://mlr3extralearners.mlr-org.com/articles/learners/list_learners.html) but for all our dictionaries?
