### ISSUE TITLE
ParamSet

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#415]
Part of basics / learner: 

* Explain parameters (also `set_values()` ...
* Mention that parameter sets are also relevant for other things like pipelines
* links to the technical section and search space section 

Marc will reduce the search_space section. What was there can either go into the basics section or into technical.

**Comment by RaphaelS1** [comment]
Can you clarify purpose of the issue? How does this differ from content in the paradox section?

**Comment by sebffischer** [comment]
The purpose here is to have a quick description in the beginning. The paradox section will be moved to technical, but we want a quick intro in the "Basics" chapter. Currently this is being done in 2.2.2 Learner API but we should write a little more.

**Comment by RaphaelS1** [comment]
Okay please can you use [this issue](https://github.com/mlr-org/mlr3book/issues/429) instead which explains this in more detail? I'm trying to remove any issues that are vague in favour of ones that can be clearly discussed and closed in PRs
