### ISSUE TITLE
Section about mathematical definitions

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#416]
We decided to put the definitions of mathematical concepts such as expected improvement into an extra "mathmetical / technical" chapter that we can refer to when explaining the concept.

**Comment by RaphaelS1** [comment]
What sort of definitions are you talking about? Some things will be simply and could go in a glossary at the end, some will be core to our work and need to be explained within the main text, some will be peripheral and could be in a separate chapter

**Comment by sebffischer** [comment]
This decision has been revoked (we decided in the workshop that we might want a section where we can put mathematical definitions of the concepts we use, e.g. empirical risk, ...) but I will close it because it is no longer planned to do this I think.
