### ISSUE TITLE
Reconsider use of internal ref() function

### ISSUE THREAD

**Issue by jemus42** [mlr-org/mlr3book#418]
In some cases like `` `r ref("resample()")` ``, the resulting output is functionally identical to the output that `downlit` already generates when `` `resample()` `` is encountered in the text.  
I'm wondering if the overhead is worth it, given that we're working around/on top of `downlit` for questionable benefit.

The `ref()` helper provides more functionality, yes, but in the simplest case I'd argue it's not worth it.

**Comment by mllg** [comment]
I haven't checked what's happening with the current version of quarto/downlit, but in the past the inline code chunks (using a single backtick) were not processed/linked. Did that change?

**Comment by jemus42** [comment]
As far as I can tell, yes. Tried it in a lokal `make serve` and the main difference is that `downlit`'d links aren't blue and underlined, but they're still links.

Not sure when you checked the last time, but quarto integrates downlit but RMarkdown/bookdown didn't (out of the box). Maybe [the approrpoate option](https://quarto.org/docs/output-formats/html-code.html#code-linking) wasn't set before?

**Comment by mllg** [comment]
AFAICT we would have two different styles of links and R6 objects are not linked (https://github.com/r-lib/downlit/issues/140). Maybe we just stick to `ref()` and wait for `downlit` to improve?

**Comment by pat-s** [comment]
I tried that during the move to `quarto` already and I think we should still with our own `ref()`. Thanks for double-checking though!
