### ISSUE TITLE
review technical book chapter

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#427]

**Comment by RaphaelS1** [comment]
I don't think issues like this are going to be useful. Too general and don't cover core issues. Suggest either: 1) closing this in favour of more specific issues for each chapter; or 2) using this as an issue where we add lots of sub-issues to it (but I don't think this is necessary as I've added labels for each chapter)

**Comment by sebffischer** [comment]
Subtasks: 
* [ ] Add section about `ParamSet`
* [ ] List what is missing

**Comment by RaphaelS1** [comment]
Hope you don't mind me editing your comment
