### ISSUE TITLE
Identify missing content in technical chapter (including unfinished sections)

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3book#430]
Please list below as required.

**Comment by RaphaelS1** [comment]
@sebffischer can you tag who was assigned to this?

**Comment by mllg** [comment]
Two points from the other issue (#442):

* parallel predict
* R6 quirks (?) ... I personally don't think this should be covered in the book though

**Comment by RaphaelS1** [comment]
I don't think we need this issue as well as #442 so I've copied the above
