### ISSUE TITLE
Don't use comments in code blocks

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#431]
We often put comments in code blocks which is kind of weird. 

Instead of 

```r
# create learner
learner = lrn("regr.rpart")
# create task 
task = tsk("mtcars")
```
 
I think we should do something like: 

create learner
```r
learner = lrn("regr.rpart")
```
create task
```r
task = tsk("mtcars")
```

**Comment by RaphaelS1** [comment]
Can I instead recommend full line-numbered code blocks with explanation after? e.g.

```R
learner = lrn("regr.rpart")
task = tsk("mtcars")
```

"Here we first create a learner and then a task"

**Comment by sebffischer** [comment]
sure this is what I meant :)

**Comment by sebffischer** [comment]
Ah sorry, didn't read properly, but I like the idea :)

**Comment by mllg** [comment]
I personally like (most) comments. Keeping code and documentation together improves readability. Additionally, it also makes it easier to keep the information together while copy-pasting stuff.

I like the line numbers for the longer explanations, though.

**Comment by RaphaelS1** [comment]
I think there's a compromise. Comments are okay for description and not explanation. So carrying on above example you could do:

```R
# construct learner
1 learner = lrn("regr.rpart")
# construct task
2 task = tsk("mtcars")
```

"Here we first create a learner and then a task"

**Comment by RaphaelS1** [comment]
Added to styleguide
