### ISSUE TITLE
Chapter 11 Comments

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3book#443]
Comments are for me so less detailed

## Style
* [x] 7.1 — Don’t isolate the reader and embrace a community! “We welcome contributions to the mlr3 ecosystem for new learners, measures, tuners, and other classes.” It’s crucial to separate between developers who want to implement something for their own research and those that want to PR to mlr3.
* [x] 7.1.4 — Use sugar everywhere.
* [x] 7.1.5 — Don’t include R6..
* [x] 7.2 — Issue with this section is that mlr3measures hasn’t really been talked about before, so it’s possible users don’t realise you need to go to this much effort to make a new measure. Otherwise very good.

## Content
* [x] General: The remit of this chapter should be made clear. So far you can add new: learners, measures, pipeops, tuners — what about filters and other extension features? ‘custom objects’ → ‘custom classes’
* [ ] 7.1.1 — This doesn’t make sense here. Users should already know how to install all packages from the first chapter. In the beginning list packages and location (CRAN, GH, R-Universe)
* [x] 7.1.2 — “RaphaelS1” → “YourGHName”.
* [ ] 7.1.5 — We’re talking about extractors and hotstarting here though it hasn’t been mentioned anywhere else in the book! Where will we discuss these? What about all the other tags like ‘threads’ and ‘required’.
* [ ] 7.1.8-7.1.9 — Need to have discussed extractors and hotstarting before this.
* [ ] 7.1.10 — Confusing, I think a remnant of something that was deleted. Also the code is hard to read. Might be better in the ParamSet section.
* [ ] 7.4 — Perhaps more detail for bbotk required. A lot more detail is required in general, look at 7.1 or 7.2 as a template. No way this can be followed by itself, there’s not even a code example. Pick a simple class and explain it.
* [ ] Make clearer why and how default parameters are changed - https://github.com/mlr-org/mlr3book/issues/270
* [ ] https://github.com/mlr-org/mlr3book/issues/271
* [ ] Stress the difference between initial values and default values (https://github.com/mlr-org/mlr3book/issues/517)

## Structure
* [ ] 7.1.11 — Doesn’t need to be a section in itself.
* [x] 7.3 — Duplicative of Chapter 5, didn’t read as I assume it’s the same. Remove from C5 and keep here.

## General

This chapter highlights technical details that should have already been discussed, e.g. hotstarting and extractors. Perhaps another chapter is required for advanced features of learners? “Basics” goes over things very quickly but then misses some very important mlr3 features

**Comment by larskotthoff** [comment]
Also revisit title -- maybe something more like "Technical and Implementation Details"?

**Comment by RaphaelS1** [comment]
If we do that then I think we need to reframe the chapter. Currently it very much is "if you want to add a class this is what you do". We could change that to "this is a lot of detail about implementation". I think latter could make more sense

**Comment by RaphaelS1** [comment]
@sebffischer I've done a first pass over the chapter and restructured. Most of my comments above relate to the learner section - please could you review this next?
