### ISSUE TITLE
Chapter 4 comments - Superseded by #453

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3book#444]
## Style

* [ ] General: Really need to unify how content is presented (english, maths, code) and to how much detail.
* [x] Diagram could be cleaned up a bit, can barely see the arrows, boxes aren’t neat, use of parantheses is confusing
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L92

→ https://github.com/mlr-org/mlr3book/pull/448

* [x] Don't print task
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L107

→ #448

* [x] This section has too much printing that doesn't add information. For example, showing the `head` of the archive is sufficient, and subset columns that are actually useful and show information, `runtime_learner` isn't useful, and you also haven't explained what the output shows. Similarly, in the benchmark_result table you're not showing any useful information, is there a missing column with an aggregated measure? If not then it really doesn't tell the user anything. Finally, the table where you score the benchmark result doesn't even show the measure! Subet by column and row!
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L198
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L221
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L232
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L239

→ #412

## Content

* [x] Definition of hyperparameters way too late. Need basic definitions early (we'll probably move into earlier chapter). A more technical discussion here about parameters and hyperpars is fine but currently this is confusing. 
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L83

→ #412

* [x] Overcomplicated and doesn't prioritise user needs. Rename to 'Terminators', list all names for sugar `trm` otherwise a user can't attempt this section
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L100

→ #448

* [x] Again users can't attempt this section as you haven't listed names for `tnr`.
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L176
* [x] Linking to wiki is terrible practice. This section is too short and doesn't have enough detail or snippets. This section should be teaching readers about all these methods and why we think they're important enough to be in mlr3. Is this list even complete? What about irace, hyperband, etc.
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L176

→ #447

* [x] First sentence is a learning opportunity, don’t say “often requires” instead point to best practice and why nested resampling is required.
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L630

→ #449

* [x] Preamble very good, good to see theory and references. Try to also address a very common Q we get “how do I use a model after optimisation with nested resampling” — something about retraining full model — maybe also include something about difference between benchmarking and train/predict. Remember you are the experts, people really value your expertise, focus for 
many readers is not just about software.
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L628

→ #449

* [x] This is the first (and only?) time in the book referring to 'stable' and 'unstable'. You make it sound like there's a method for separating between the two. Similarly you print output to supposedly investigate stability but don't make clear if they're stable or not or even explain how to read the output. Instead you could show an example where you tune two parameters and plot their arguments over iterations to show the difference in 'stability'?
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L699-L702

→ #449

* [x] You use the `$score` method but don’t display the result but instead different columns. Subset!
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L712

→ #449

* [x] Can you really say the model is unbiased?
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L715

* [ ] Needs **a lot** more detail. This is a very important topic to a lot of people and is currently just 3 sentences. This is where team expertise shine beyond code implementation
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L726

→ #449

## Structure
* [x] General: Needs a clear intro and conclusion. Need to properly think about making this two separate chapters, one for tuning and one for feature selection. 

→ #412

* [x] So much printing and discussion early on that reader forgets point of the section. Make clear the purpose of the section, and slowly show most relevant components, then a longer example. At the moment I find myself jumping between old and new content too quickly.
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L100

→ #448

* [ ] Ordering is confusing. Archive and manual tuning is tricky. Show some clear examples up front that tackle most common use-cases. Clearly state when you manually tune, for example answering a FAQ “how do I use a model after benchmarking”.
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L198
* [x] This is one of the most powerful parts of mlr3 and this should be more clearly highlighted.
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L297 
* [x] Search spaces have already been used earlier in the chapter, so an intro to paradox doesn't make sense here. Basics should go in chapter 2, and be removed from this section. Needs to be figured out with #439 and #442
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L354
* [x] Execution of what? Why is this a standalone section?
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L656
* [x] Unclear why this is standalone section.
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L694

* [x] Strongly suggest removing from here and put in a gallery post
https://github.com/mlr-org/mlr3book/blob/ac3f3b95eee0f4d1556734d83d05860596ad4c16/book/optimization.qmd#L742

→ #412

## Introduction (@pfistfl @sumny)

Organize the introduction around the following topics: 
- [ ] Motivation
- [ ] Basic Concepts 
    - [ ] What are the basic concepts we'll need to know? 
    - [ ] What are the `mlr3` objects we will interact with?
    - [ ] Can we visualize that nicely?
- [ ] Further Reading 
  - [ ] What topics within the book are relevant?
  - [ ] Point  to references and additional (outside) links

**Comment by RaphaelS1** [comment]
Updated some comments in light of https://github.com/mlr-org/mlr3book/pull/412 but need to re-review

**Comment by be-marc** [comment]
>  Don't print task

Don't use the `print` function or don't print already introduced objects (task, measure, resampling) at all?

**Comment by RaphaelS1** [comment]
> >  Don't print task
> 
> @RaphaelS1 Don't use the `print` function or don't print already introduced objects (task, measure, resampling) at all? 
> 

Both! Don't use `print` if it isn't required (as the style is inconsistent with other chapters) and don't reprint objects like tasks and measures that always look the same

**Comment by be-marc** [comment]
> This is the first (and only?) time in the book referring to 'stable' and 'unstable'. You make it sound like there's a method for separating between the two. Similarly you print output to supposedly investigate stability but don't make clear if they're stable or not or even explain how to read the output. Instead you could show an example where you tune two parameters and plot their arguments over iterations to show the difference in 'stability'?

I removed this part. There could also be several good configurations that differ significantly.

**Comment by be-marc** [comment]
> Can you really say the model is unbiased?

The estimated performance of the model is unbiased. We have discussed this several times. Bernd thinks that the sentence is okay like this.

**Comment by be-marc** [comment]
>  Needs a lot more detail. This is a very important topic to a lot of people and is currently just 3 sentences. This is where team expertise shine beyond code implementation

Do you have a suggestion for more content?

**Comment by be-marc** [comment]
@RaphaelS1 I will merge #449 today. I need a new review. Maybe in a new issue? You can copy the last outstanding issues.

**Comment by RaphaelS1** [comment]
> The estimated performance of the model is unbiased. We have discussed this several times. Bernd thinks that the sentence is okay like this.

Yeah but the underlying prediction might not be because data bias etc. etc. I'm not saying it's technically wrong (and definitely trust Bernd) but just think that words like this could confuse readers? Very happy to be overuled on this

**Comment by RaphaelS1** [comment]
> > Needs a lot more detail. This is a very important topic to a lot of people and is currently just 3 sentences. This is where team expertise shine beyond code implementation
> 
> Do you have a suggestion for more content?

I think basically the issue is that you have a section for something important but then reduce it to a few small lines. One way to fix this could even be to have an example at the _beginning_ of the chapter that shows the end result, i.e. a tuned learner that can be trained and tested. Or change this section to be called "putting it all together" and then just put together one long example that shows tuning, training, testing, evaluating.

**Comment by RaphaelS1** [comment]
> @RaphaelS1 I will merge https://github.com/mlr-org/mlr3book/pull/449 today. I need a new review. Maybe in a new issue? You can copy the last outstanding issues.

Lol was about to say I'd review in branch but see you've already merged. No worries I'll review in new issue and copy over as suggested.

**Comment by be-marc** [comment]
> Lol was about to say I'd review in branch but see you've already merged. No worries I'll review in new issue and copy over as suggested.

Ah sorry. I mean a review for the whole chapter.

**Comment by be-marc** [comment]
> Yeah but the underlying prediction might not be because data bias etc. etc. I'm not saying it's technically wrong (and definitely trust Bernd) but just think that words like this could confuse readers? Very happy to be overuled on this

Yes, we should address this. I will add: Note that the predictions of the models could still be biased e.g. due to a bias in the data.

**Comment by RaphaelS1** [comment]
Superceded by #453
