### ISSUE TITLE
Chapter 4v2 comments

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3book#453]
Thanks @be-marc for the quick revisions to the chapter. Happy to say many of the issues closed so quickly! Below I've copied over remaining issues, added conversations from MM and GH, and added new issues.

## Issues still open from #444 (with added comments)

* [x] Still missing list of terminators. It isn't enough to say "listed on website" - readers of the book shouldn't have to depend on having the website open at the same time for critical functionality - also the link doesn't describe what they do. For example what is `trm("none")`? I don't understand the use-case.
* [x] Listing tuners in one paragraph doesn't look great. I'd suggest bullet points with a unified structure like:
* Grid search (`"grid_search"`) - Discretizes the range of each HPC and exhaustively evaluates each combination (or until termination is reached according to the given `trm`)
* Random search (`"random_search"`) - Samples HPCs from a uniform distribution randomly. 

Then *after* you've objectively listed them you can then say things like "basic tuners like grid and random search may be inefficient and more advanced tuners like irace and....." - i.e., be objective and then insert expert opinion. By doing this you can also go into as much technical detail as you like (but don't write a section on hyperband!).

Do the same for terminators. You've lost discussion about annealing and non-linear optimization, was this deliberate?

* [x] You've lost discussion about stable/unstable parameters. I wonder if it's worth a brief paragraph explaining why we often don't care about stability, e.g. for naive methods like grid and random search we don't expect stability. But for advanced methods like irace we might expect this to be guarnateed as the alg converges (this could go above in the discussion about tuner methods?)

* [x] As discussed make the conversation around the predictions being 'unbiased' a bit more nuanced.
* [x] As discussed, the 'Final Model' section is very out of place. The key message in this section is "now you're tuned your model you can make use of the rest of the mlr interface like normal" therefore I'd consider handling this in one of two ways: 1) rename as "Putting this all together" and show one worked example including choosing a model (e.g. random forest), selecting hyper-parameters to tune and why (e.g., we know that number of splits, number of trees, and terminal nodes are often most important), selecting terminator and tuning method (and again why, in this case irace would be good because multiple parameters), then tune the model, train it, make predictions, and evaluate. OR 2) write a single sentence not in a new section that just says "now the model can be trained like any other mlr3 learner, try this out for yourself in the exercises at the end of this chapter" then we'll add some exercises.
* [x] Intro is great but you still need a conclusion. What did we learn? Table linking S3 to R6. Exercises.
* [ ] I don't think you've addressed this point: (Use text not code)
>  Archive and manual tuning is tricky. Show some clear examples up front that tackle most common use-cases. Clearly state when you manually tune, for example answering a FAQ “how do I use a model after benchmarking”.

## Generic Style

Please look at everything in #434. I won't highlight particular issues here but will copy over comments that I see apply:

* [x] Avoid external hyperlinks unless strictly required
* [x] Be consistent with call-out boxes
* [x] Format code as below. Links to internal API fine but remember these won't be rendered in print:
  * `package`
  * `package::function()`
  * `function()`
  * `$field`
  * `$method()`
* [x]  Reference figures, tables, and other environments (Fig X, Table X). In general don't assume placement unless it's a code chunk
* [x] R6 Classes (unless need to explicit discuss different paradigms)
* [x] When introducing new important functions, write out the full signature and describe parameters the first time, when 'calling' methods omit parameter names, e.g.

> `as_task_regr(x, target, id=deparse(substitute(x))`
> * x - Backend for converting to task
> * target - Dependent variable
> * id - Name of newly created task

> For example
> `as_task_regr(iris, "sepal_length", "flowers")`
* [x] In the main body of text use sugar functions. At the end of each chapter include a conclusion that contains a mini API/reference to cover key functions learnt in that chapter, here include a table that shows R6 mappings so readers know how to have more flexibility. e.g.

| S3 sugar function | R6 underlying class | 
| --- | --- |
| `as_task_regr` | TaskRegr$new(id, backend, target) | 

### Style

* [x] This is very bad practice. Users will be incredibly confused if what you're printing isn't what the code shows. Just show them the subsetting statement.
https://github.com/mlr-org/mlr3book/blob/941a3e5f4272f10b7ff67d62da1047daa2e2fa6b/book/optimization.qmd#L446-L454

### Content

**Introduction**

* [x] Haven't actually explained what a HPC is
https://github.com/mlr-org/mlr3book/blob/9f8d15c974ca94500d53a09b3bab9a898ffa598f/book/optimization.qmd#L8
* [x] This is too technical for this early in the chapter. You haven't defined a search space?
https://github.com/mlr-org/mlr3book/blob/9f8d15c974ca94500d53a09b3bab9a898ffa598f/book/optimization.qmd#L11
* [x] My guess is similar acronyms early on will confuse people. --> Remove 'HPC' and just use 'Configuration' - check we mean HPC everywhere when the word 'configuration' is used
https://github.com/mlr-org/mlr3book/blob/9f8d15c974ca94500d53a09b3bab9a898ffa598f/book/optimization.qmd#L12
* [x] Because you link to tuners you're implicitly telling web-readers they're the same thing but not book readers. So instead suggest `HPO methods (or 'tuners')`. Avoid phrases like 'the HPO problem' as it's not immediately clear that 'the problem' refers to HPO itself, just say 'HPO'!
https://github.com/mlr-org/mlr3book/blob/9f8d15c974ca94500d53a09b3bab9a898ffa598f/book/optimization.qmd#L16
* [x] Again you're not defining the key terms and the language is too technical. What's a termination criterion? What does it mean in this context?
https://github.com/mlr-org/mlr3book/blob/9f8d15c974ca94500d53a09b3bab9a898ffa598f/book/optimization.qmd#L17
* [x] General: too technical too quickly. Detail is great but just remember that you need to explain all terms early

**Model Tuning**

* [x] Remove, we'll introduce mlr3verse in Chapter 2 (#439)
https://github.com/mlr-org/mlr3book/blob/9f8d15c974ca94500d53a09b3bab9a898ffa598f/book/optimization.qmd#L37-L41
* [x] The issue with this phrasing is that it doesn't actually reflect the section structure. What you're doing in this section is explaining each component separately and then combining them in the final section. You still need to learn about tuners and terminators to use `tune`. It's actually irrelevant if you use `ti` or `tune`. Similarly 'Analysing the Result' is the same whether you use `ti` or `tune` but this is unclear in the current structure. So intead I suggest the following order: 4.1.0 Introduction explain `Instance` is important and say there's two ways to make use of it, either consutrcting one manually with `ti` or automated with `tune`. 4.1.1 Terminators. 4.1.2. Tuners. 4.1.3 Tuning Instance (including triggering). 4.1.4 Tune. 4.1.5 Analysing result. 4.1.6 Putting it all together (final model, analyse, train/predict on new data).
https://github.com/mlr-org/mlr3book/blob/9f8d15c974ca94500d53a09b3bab9a898ffa598f/book/optimization.qmd#L48-L51

___

## Introduction (@pfistfl @sumny)

Organize the introduction around the following topics: 
- [x] Motivation
- [x] Basic Concepts 
    - [x] What are the basic concepts we'll need to know? 
    - [x] What are the `mlr3` objects we will interact with?
    - [x] Can we visualize that nicely?
- [x] Further Reading 
  - [x] What topics within the book are relevant?
  - [x] Point  to references and additional (outside) links

**Comment by RaphaelS1** [comment]
@be-marc great revisions - thanks a lot. I haven't done a complete detailed review as I think there are some major changes that need to happen first. 

1. I'd suggest restructuring 4.1 as written above as this will make it clearer to read I think
2. don't mask what code is actually being written. better for the code to be slightly messier (but honest) than the output to be messy

**Comment by RaphaelS1** [comment]
Ping me when the major things are done and I'll do a detailed review.

**Comment by be-marc** [comment]
Thanks! Work in #457.

**Comment by be-marc** [comment]
> The issue with this phrasing is that it doesn't actually reflect the section structure. What you're doing in this section is explaining each component separately and then combining them in the final section. You still need to learn about tuners and terminators to use tune. It's actually irrelevant if you use ti or tune. Similarly 'Analysing the Result' is the same whether you use ti or tune but this is unclear in the current structure. So intead I suggest the following order: 4.1.0 Introduction explain Instance is important and say there's two ways to make use of it, either consutrcting one manually with ti or automated with tune. 4.1.1 Terminators. 4.1.2. Tuners. 4.1.3 Tuning Instance (including triggering). 4.1.4 Tune. 4.1.5 Analysing result. 4.1.6 Putting it all together (final model, analyse, train/predict on new data).

That's a good comment. I would do it a little differently though. 

4.1.0 Small introduction to tuning instance and tuner.  And the problem (including learner and task)
4.1.1 Learner and Search Space
4.1.2 Terminator
4.1.3 Tuning Instance (including measure and resampling)
4.1.4 Tuners
4.1.5 Triggering the Tuning
4.1.6 Tune
4.1.7 Analyzing the Results
4.1.8 Fit Final Model

Keep the Tuner section after Tuning Instance. The tuning instance is passed to the tuner, so the sections have the same sequence as the code.

**Comment by be-marc** [comment]
> As discussed, the 'Final Model' section is very out of place. The key message in this section is "now you're tuned your model you can make use of the rest of the mlr interface like normal" therefore I'd consider handling this in one of two ways: 1) rename as "Putting this all together" and show one worked example including choosing a model (e.g. random forest), selecting hyper-parameters to tune and why (e.g., we know that number of splits, number of trees, and terminal nodes are often most important), selecting terminator and tuning method (and again why, in this case irace would be good because multiple parameters), then tune the model, train it, make predictions, and evaluate. OR 2) write a single sentence not in a new section that just says "now the model can be trained like any other mlr3 learner, try this out for yourself in the exercises at the end of this chapter" then we'll add some exercises.

I repeat the tuning code in this section now. But I would not change the example here and stick to rpart on penguins.

**Comment by be-marc** [comment]
I added two exercises. The solution is in a folded code block. For the book we need something like a Solutions section in the appendix.

**Comment by be-marc** [comment]
> As discussed make the conversation around the predictions being 'unbiased' a bit more nuanced.

The aggregated performance of all outer resampling iterations is essentially the unbiased performance of the model with optimal hyperparameters found by grid search.
This classification error should be reported as the performance of the final model.
Note that the term *unbiased* only refers to the statistical procedure of the performance estimation.
The underlying prediction of the model could still be biased e.g. due to a bias in the data set.
In this case, the performance estimate of the model would be also biased.

**Comment by be-marc** [comment]
> Archive and manual tuning is tricky. Show some clear examples up front that tackle most common use-cases. Clearly state when you manually tune, for example answering a FAQ “how do I use a model after benchmarking”.
 
1. We cover the manual approach here first because it gives you a better understanding of mlr3tuning.
2. This option gives you more control over the tuning process.

More?

> Show some clear examples up front that tackle most common use-cases

What examples do you mean?

**Comment by RaphaelS1** [comment]
> > The issue with this phrasing is that it doesn't actually reflect the section structure. What you're doing in this section is explaining each component separately and then combining them in the final section. You still need to learn about tuners and terminators to use tune. It's actually irrelevant if you use ti or tune. Similarly 'Analysing the Result' is the same whether you use ti or tune but this is unclear in the current structure. So intead I suggest the following order: 4.1.0 Introduction explain Instance is important and say there's two ways to make use of it, either consutrcting one manually with ti or automated with tune. 4.1.1 Terminators. 4.1.2. Tuners. 4.1.3 Tuning Instance (including triggering). 4.1.4 Tune. 4.1.5 Analysing result. 4.1.6 Putting it all together (final model, analyse, train/predict on new data).
> 
> That's a good comment. I would do it a little differently though.
> 
> 4.1.0 Small introduction to tuning instance and tuner. And the problem (including learner and task) 4.1.1 Learner and Search Space 4.1.2 Terminator 4.1.3 Tuning Instance (including measure and resampling) 4.1.4 Tuners 4.1.5 Triggering the Tuning 4.1.6 Tune 4.1.7 Analyzing the Results 4.1.8 Fit Final Model
> 
> Keep the Tuner section after Tuning Instance. The tuning instance is passed to the tuner, so the sections have the same sequence as the code.

Sorry but again 'Fit Final Model' does *not* make sense - it's too small a section in it's own right. Framing as 'putting it all together' is much more interesting for a reader to see one long but concise example. Readers won't care about fitting by itself. Also your structure still has the same issue, it will be *very* repetitive. Users need to be able to understand that you're essentially giving two separate ways to do the same thing. If you structure as you've suggested then this is how it reads to a reader:

4.1.0 Learn what a tuning instance and tuner is
4.1.1 Learn about how to use paradox in the context of search space (builds on knowledge from previous hyperparameter chapters)
4.1.2 Learn how to **end** tuning before we even know how to start tuning (I know I'm now going against my original suggestion)
4.1.3 Learn about a very complex abstract idea called a TuningInstance
4.1.4 Learn about algorithms for tuning
4.1.5 Learn how to pass instances to tuners and run one method (this is like 2 lines of code)
4.1.6 Learn that 4.1.3 was basically not needed
4.1.7 Looking into archive and tuning results
4.1.8 Learn that you can call `$train` (which is obvious once you're told it's a learner)

Whilst I really appreciate the need to explain Instance as it's the core component, it's also just not the easy and intuitive way to use your own code. And I really worry that users are going to see this as unneccessary.

BUT for now I'd suggest writing as you suggest and then when the content is done it'll be much easier to discuss structure (we can also do this over a call)

**Comment by RaphaelS1** [comment]
> > As discussed, the 'Final Model' section is very out of place. The key message in this section is "now you're tuned your model you can make use of the rest of the mlr interface like normal" therefore I'd consider handling this in one of two ways: 1) rename as "Putting this all together" and show one worked example including choosing a model (e.g. random forest), selecting hyper-parameters to tune and why (e.g., we know that number of splits, number of trees, and terminal nodes are often most important), selecting terminator and tuning method (and again why, in this case irace would be good because multiple parameters), then tune the model, train it, make predictions, and evaluate. OR 2) write a single sentence not in a new section that just says "now the model can be trained like any other mlr3 learner, try this out for yourself in the exercises at the end of this chapter" then we'll add some exercises.
> 
> I repeat the tuning code in this section now. But I would not change the example and stick to rpart on penguins. I like the idea of exercises at the end.

I'm not saying change example, just make sure you explain it in detail

**Comment by RaphaelS1** [comment]
> I added two exercises. The solution is in a folded code block. For the book we need something like a Solutions section in the appendix.

I think we should have online solutions - we don't need to waste page count. I can create an appendix for this now which we won't put in print book

**Comment by RaphaelS1** [comment]
> > As discussed make the conversation around the predictions being 'unbiased' a bit more nuanced.
> 
> The aggregated performance of all outer resampling iterations is essentially the unbiased performance of the model with optimal hyperparameters found by grid search. This classification error should be reported as the performance of the final model. Note that the term _unbiased_ only refers to the statistical procedure of the performance estimation. The underlying prediction of the model could still be biased e.g. due to a bias in the data set. In this case, the performance estimate of the model would be also biased.

Perfect, make sure this is in there!

**Comment by RaphaelS1** [comment]
> > Archive and manual tuning is tricky. Show some clear examples up front that tackle most common use-cases. Clearly state when you manually tune, for example answering a FAQ “how do I use a model after benchmarking”.
> 
>     1. We cover the manual approach here first because it gives you a better understanding of mlr3tuning.
> 
>     2. This option gives you more control over the tuning process.
> 
> 
> More?

I think this is good but doesn't need to be bullet points. "We discuss the manual approach first as it provides a better understanding of mlr3tuning and the different options that a user can change to control the tuning process in detail."

**Comment by RaphaelS1** [comment]
> What examples do you mean?

Okay so two examples maybe:

1. Based on the FAQ "how do I use the best tuned model from a benchmark experiment". 1) small benchmark experiment including autotuned model; 2) retune best model and inspect optimal configuration; 3) set hyper-parameters based on these; 4) retrain for future prediction.
2. Very simple dummy example: tune elasticnet model to pick between lasso and regression.

**Comment by be-marc** [comment]
## Bernd's comments

- [ ] Tune svm with grid search
- [ ] The tuning should produce significant results
- [ ] Expand search spaces section
- [ ] Explain logscale  in more detail
- [ ] Add advanced search space section to the end of 4.1
- [ ] Make multi-crit tuning section 4.2
- [ ] Explain that hyperband and mbo are in separate packages
- [ ] What is grid resolution
- [ ] Add paragraph about control parameters of the tuners
- [ ] References for algorithms
- [ ] Explain the archive in more detail e.g. print column names
- [ ] Paragraph about fallback learner and runtime limits at the end of 4.1
- [ ] Show `as.data.table` with an extra measure
- [ ] Don't use train time measure
- [ ] Cite HPO paper in 4.3
- [ ] Link to gallery posts
- [ ] Show `extract_innner_tuning_archives`
- [ ] mlr3tuningspaces section

**Comment by RaphaelS1** [comment]
Agreed with all _except_ a lot of people care aout train time. So at least mention it

**Comment by be-marc** [comment]
@RaphaelS1 I'm done again for now. Maybe we should have a meeting with Bernd and Lennart next. If you want, you can also review the chapter beforehand and merge. This version should be already much better.

@sumny We can also wait until you finish the mbo sections.

**Comment by RaphaelS1** [comment]
Thanks @be-marc can you let me know why some of the things are unchecked?

**Comment by be-marc** [comment]
https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L31

Why did you start writing multiple sentences into one line?
The git diffs are harder to read this way.

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L33-L44

This code is really ugly. Please let's not start the chapter like this. Instead, we could (1) style the code with more intermediate steps,  (2) only show the plot and write about manual tuning, (3) remove the code and plot, and only write about manual tuning (4) don't show manual tuning at all. I am in favor of option 2 or 4.

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L56-L72

I prefer the diagram with the simple HPO loop at this point. So early in the chapter, the user doesn't know much about the individual components. We could show this diagram later.

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L87

We should not start describing every detail and possibility. The information about nu classification is not important for the user.

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L117

I think the Quarto boxes are better.

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L119

Does  [log(1e-5), log(1e5)] get a style?

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L121-L125

I would prefer a histogram instead of code that the user does not need.

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L129

I am still against showing the tuner with the components that build the instance. This is also clearly separated in the code. First, you create the tuning problem (tuning instance), and then you use the optimizer to solve it. I understand that it is a bit odd to show the terminator before the tuner. But I think the reader is smart enough to understand that. Mixing tuner and instance is much more confusing.

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L196-L197

We might have to rephrase that. The difference is that the tuning starts directly. Defining the instance is more or less the same.

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L214-L216

Again, we should not describe every detail. We don't use hotstarting in the chapter. So why do we show the option here?

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L260

Same point as on line 197.

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L289

Why do we use `head()`? `datatable.print.nrows` is much better. You can see head and tail at the same time. `head()` only makes the code longer.

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L560-L581

Is this diagram really helpful?

https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L612

Nested resampling is the most complicated part of the chapter. Why is there only one section now? Is the AutoTuner explained in another chapter?

**Comment by RaphaelS1** [comment]
@be-marc I've added your comments Bernd agreed on Friday to https://github.com/mlr-org/mlr3book/pull/457 so closing this issue
