### ISSUE TITLE
Bernd comments, intro

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr3book#454]
- something to explain dictionaries, in general and specifically to mlr3
- R6 vs syntactic sugar; quick description at the end of R6 intro

**Comment by RaphaelS1** [comment]
https://github.com/mlr-org/mlr3book/issues/432
https://github.com/mlr-org/mlr3book/issues/437
https://github.com/mlr-org/mlr3book/issues/439

I think these are covered here

**Comment by larskotthoff** [comment]
Thanks, yes, this is just to keep track of things Bernd brought up.

**Comment by RaphaelS1** [comment]
Not sure this makes sense as a way of keeping track of these things or we'll just get duplication - i.e., it isn't clear here what chapter or section this refers?

**Comment by larskotthoff** [comment]
I'm happy to close this here, as we keep track elsewhere.
