### ISSUE TITLE
Chapter 1v2 comments

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3book#484]
Amazing work! Just a few small comments

## Old comments

* [x] I think we still need a little more for the comparison to caret and tidymodels. It doesn't quite get at what mlr does better/worse. e.g., we could explicitly say that tidymodels may be better for simply fit/predict but mlr has more advanced functionality and possibly more implemented models/learners.
* [x] Add section on mlr3viz
* [x] Please mark Design Principles section with [this](https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L344-L346). (I'm unsure if this is definitely what we'll use going forward but better to unify for now then we can fix later)
* I noticed the R6 section is the same but tbh reading again I think it looks good so happy you ignored the comment

## New comments

* [x] Please add front matter with details of authors; and
* [x] 150-200 word abstract (see [here](https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L1-L14))
* [x] For external hyperlinks that are not to functions or packages, please use the function `link` I've created which makes links accessible for people reading the published book (you'll need to wait until #457 is merged / until I pull out the function from that PR but no rush on this)
* [x] Please add `fig-alt` to all figures to create alternative text for screen-readers, see an example of this [here](https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L36)
* [x] Please add a section on dictionaries and write a bit more more about sugar

**Comment by larskotthoff** [comment]
Thanks, what in particular are you missing in the sugar section?

**Comment by RaphaelS1** [comment]
I think it's 99% there but is just easy to miss and indeed I scrolled past it on my first read. I think maybe just add a heading (e.g., ### Sugar functions {.unnumbered .unlisted}) to make it stand out and possibly just give a very short one line example, e.g. take your Rpart example and add the R6 equivalent - just so users get a clear idea of the difference in code syntax and usability.

**Comment by larskotthoff** [comment]
I've addressed most of these. What do you have in mind for the mlr3viz section? It's mentioned in the text and the chapter doesn't talk about any packages in particular, so I'm unsure what to do here.

Is an abstract necessary here?

**Comment by larskotthoff** [comment]
Hmm, I'm wondering whether this would be too much up front. In particular as with chapter 2 we've gone the other way -- not talk so much about things up front and introduce them as we go through the example instead. For all of R6, sugar, dictionaries, mlr3viz we can explain this (and do to some extent already) when it comes up.

I'm worried that having so much "dry" stuff up front may turn readers away. In particular as I don't think it's necessary -- when the reader first encounters e.g. dictionaries we can simply add a sentence or two to explain. And the example will be right there, in context.

**Comment by RaphaelS1** [comment]
To me this comes down to two questions: 1) how will people read the book; 2) are these things 'basic'?

So 1) can we depend on people reading cover to cover? I don't think we can. A lot of people who buy the physical book will use it as a reference and are likely to have it open on desks whilst writing their own code - it's unlikely they'll be focusing on chapter 2. So depending on content there is imo a mistake as Chapter 1 is the more natural place.

For 2) these things are imo *not* basic. mlr3viz is an entire extension pkg, talking about it in Chapter 2 is therefore the wrong place as it's not 'basic' (which to me just means mlr3 and mlr3learners). Similarly discussing dictionaries and sugar fully in Chapter 2 may also put too much on new users.

I'm very happy to be convinced either way. Maybe we need a tiebreaker opinion? @mllg @berndbischl thoughts?

**Comment by larskotthoff** [comment]
Also add brief intro to ML in general.

**Comment by larskotthoff** [comment]
- Remove ref to mlr3shiny, extend description for OO.
- Revisit data.table section when we know what of data.table is used in the rest of the book (list columns).

**Comment by RaphaelS1** [comment]
@larskotthoff  can this be closed? Have comments above been addressed?
