### ISSUE TITLE
Chapter 5v2

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3book#490]
## Overall comments

This is a really nice short chapter that flows well and is well-written but there's something missing. Unlike other chapters it does a good job of showing cool features but it doesn't feel 'exciting' to read as you don't get an idea of the breadth of features offered, i.e. because you only refer to the appendix and don't list filters of methods the reader doesn't get an idea of what's availability or how to use it. As I've said in other chapter comments, list the available methods here (doesn't need to be all but a subset) and give some personal theroretical perspective. What do the methods do?  What do you recommend people use? Look [here](https://github.com/mlr-org/mlr3book/blob/07714b769f94067b2dd550e27d481179272ebc14/book/optimization.qmd#L133-L146) for examples. 

### General

* [x] Please add front matter with details of authors; and
* [x] 150-200 word abstract (see [here](https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L1-L14))
* [x] For external hyperlinks that are not to functions or packages, please use the function `link` I've created which makes links accessible for people reading the published book
* [x] Please add `fig-alt` to all figures to create alternative text for screen-readers, see an example of this [here](https://github.com/mlr-org/mlr3book/blob/dfb3459056f1fd0e32ad62a0524fa17adec3db04/book/optimization.qmd#L36)
* [x] Please add exercises to the end of the chapter ([e.g.](https://github.com/mlr-org/mlr3book/blob/07714b769f94067b2dd550e27d481179272ebc14/book/optimization.qmd#L707))
* [x] Please add resources ([e.g.](https://github.com/mlr-org/mlr3book/blob/07714b769f94067b2dd550e27d481179272ebc14/book/optimization.qmd#L698)) (i.e, cheatsheets) to the end of the chapter -- 'Further reading' could also go here
* [x] Please add a S3 <> R6 reference to the end ([e.g.](https://github.com/mlr-org/mlr3book/blob/07714b769f94067b2dd550e27d481179272ebc14/book/optimization.qmd#L686))
* [x] Please add a conclusion to the end ([e.g.](https://github.com/mlr-org/mlr3book/blob/07714b769f94067b2dd550e27d481179272ebc14/book/optimization.qmd#L682))
* [x] Don't need to write 'Introduction' for introduction
* [x] Please subset archives by column as well as row to avoid the "variables not shown" message (which will look very bad when printed). Also note that the score column isn't shown currently. 
* [x] Several links in the chapter (e.g. very first) seem broken, please remove them
* [x] Please refer to chapters using `@` and not with `#`, e.g. "[Filters](#fs-filter)" -> "@fs-filter"
* [x] Please use quarto prefixes for cross-referencing, including sections. e.g. "{#fs-filter}" -> "{#sec-fs-filter}"

## 5.2 Filters

* [x] In 5.2.1 you talk about calculating the information gain filter but haven't said what this filter does or what those values mean, please add theoretical detail for all examples
* [x] I found the description of embedded methods in 5.2.3 a bit confusing to follow. Do embedded methods *always* use `selected_features` under the hood? If so this should be explicitly stated because currently it just looks like a specific example
* [ ] I think this chapter needs to go _after_  the Pipelines as it refers to pipelines (and tbh is simpler to use with pipelines than without), @berndbischl do you agree?
* [x] Please add captions and alternative text to all figures ([e.g.](https://github.com/mlr-org/mlr3book/blob/07714b769f94067b2dd550e27d481179272ebc14/book/optimization.qmd#L592-L594))

## 5.3 Wrapper Methods

* [x] Whole section reads very 'samey' to Chapter 4. I think it's safe to tell people to read relevant sections in Chapter 4 and then come back to Chapter 5, you shouldn't need to repeat text. Instead you could simplify by saying something like "this works analogously to optimisation in Chapter 4, with these classes instead.......and we even use the same terminators!...." Similarly all the stuff about multiple measures and automating the procedure, that's basically identical to Chapter 4. So I think for this whole section just write out the differences between this chapter and the previous, then demonstrate in clear examples.
* [x] Use `=` not `<-`

**Comment by mnwright** [comment]
All comments addressed in #504 and reviewed with @berndbischl. The question whether this chapter should go before pipelines is still open and in discussion. But I think we don't have to keep this issue open for that.
