### ISSUE TITLE
PDF version link broken 

### ISSUE THREAD

**Issue by waynelapierre** [mlr-org/mlr3book#498]
### Description

https://mlr3book.mlr-org.com/mlr3book.pdf

This link is broken. 

### Reproducible example

NA

**Comment by RaphaelS1** [comment]
Can you tell us where you found the link so we can fix it? New pdf link here

https://mlr3book.mlr-org.com/Flexible-and-Robust-Machine-Learning-Using-mlr3-in-R.pdf

**Comment by waynelapierre** [comment]
https://github.com/mlr-org/mlr3book

**Comment by mllg** [comment]
Fixed in README
