### ISSUE TITLE
Comments From start until chapter basics

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#499]
I was reading the first few chapters and just wrote some things down that I noticed. I hope the notes are not too pedantic, if so please ignore. 

## Getting Started

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/index.qmd#L25

I would remove the "upcoming" so we don't forget to fix it when the book is then actually published. 

## Preface

In general: we should always refer to the mlr-org website as additional material earlier on. 

Also under "Design Principles" should we list something like "Explicit is better than implicit", i.e. that mlr3 does less internal conversions than mlr? 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/preface.qmd#L45

mlr3pipelines is included in mlr3verse so we dont need to load it

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/preface.qmd#L94

Chapter preprocessing is missing

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/preface.qmd#L97

I guess some things (e.g. paradox) are missing here. 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/preface.qmd#L111

Maybe here we can also reference the renv.lock in the mlr3book repository

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/preface.qmd#L147

Link to mlr-org overview website instead

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/preface.qmd#L152

mention what mattermost is

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/preface.qmd#L166

Bug reports about mlr3learners should be opened in mlr3learners ... 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/preface.qmd#L143

Usually we use <...> instead of {...}

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/preface.qmd#L225

  * How do we refer to objects, e.g. a `data.frame`?
  * also we refer to R functions from the R standard library without the e.g.  `utils::` prefix

## Chapter 1

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/intro.qmd#L95

I think we should rather link to the website: https://mlr-org.com/ecosystem.html In general it does not make sense to keep both lists. I guess we can remove it from the wiki as it is already on the website. 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/intro.qmd#L105

I would not phrase it like that. This kind of makes it seem like R6 is an improved S3, but it is rather an improved version of reference classes no.

## Chapter 2

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L22

Technically this is not true as we have the insample resampling. 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L26

typo

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L32

This sentence is not too clear I think. A single train-test split (because in mlr3 terms a resampling can also be a cross validation which contains multiple train test splits)

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L51

to a new variable

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L59

to get more information about one of those predefined tasks

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L97

In the preface we say that we refer to mlr3 functions without the `mlr3::` prefix, so what is right here? I think we need to update the `ref()` function

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L98

We are not referring to the `data.frame()` function here, so I guess `data.frame` would be better. 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L165

Link to the corresponding section and maybe mention SQLite or something

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L173

If it takes more characters it is not really a shortcut

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L239

This was already mentioned a couple lines earlier

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L276

Role validation does not exist anymore, there are now the roles holdout and test

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L296

Here we could link to the Extending section in case a learner that someone wants to use is not available

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L308

is annotated with

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L310

I don't think we have mentioned feature types before, so either mention it before or do some explaining here. Also for the html version give a link. The same holds for properties 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L322

Maybe mention hotstarting here? Hotstarting is only mentioned in the extending section so I think we should add something somewhere in the book.

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L354 

Uses them to partition the feature space

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L377

When the new paradox version is released we should mention the method `param_set$set_values(...)` which adds some more convenience. 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L459

To ALSO predict these standard errors. (I think one might naturally think that when setting the predict type to se, only the se is predicted)

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L487

Link to the extending section on how to add measures. 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L503

The  "this is why..." does not really explain the sentence before but a different concept imho

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L539

the ids of ... start with ... 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L550

penguins is from the palmerpenguins R package.

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L567

According to the preface, mlr3 intern functions are not referenced with the mlr3viz:: prefix

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L557

I think here it would also be nice to explain why the task has the property "multiclass". 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L562

unique(task_penguins$data(cols = "species")[[1]]) would result in a less space consuming output. 

* [ ] We load the mlr3viz library multiple times in the same chapter. I guess it is enough to do it once per chapter, so I guess those can be removed: 

1. https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L450

2. https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L571

3. https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L603

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L628

Do we really want to print all the measures here, maybe just show some and give a link to the mlr-org website to the measures

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L652

Technically this sentence is not correct. It does not give information as to WHICH observations are misclassified. 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L657

through the confusion FIELD

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L713

Remove the mlr3cluster and mlr3proba prefix in the reference 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L725

mlr3cluster and mlr3proba also implement learners

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L727

dEliberately

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L730

I would not mention the fallback learner here, as the concept has not been introduced at all so far. Also I think a table might look nicer than the current bullet list. Maybe we can also create this table programatically as otherwise we will probably forget updating the list when we add learners to mlr3learners ... 

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L750

and GROWS as packages are loaded

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/basics.qmd#L755

You can list all learners that are available through the packages that you have loaded in your R session by calling ... 

## Appendices

* [ ] https://github.com/mlr-org/mlr3book/blob/eea1af8ac772a11c9e0a4883f080a45f6ab8e304/book/session.qmd#L6 

We need to load all relevant packages from the renv.lock before calling sessionInfo()

**Comment by RaphaelS1** [comment]
Thanks for these comments. It would probably be quicker if you made PRs for things like typos and other small suggestions, especially as it's quite difficult to go through a long list related to multiple different chapters and have to agree/disagree with each separately. Can I also recommend splitting this into individual issues or comments on open PRs? The overall review is very useful but currently chapters are in the middle of review cycles so for anything larger than typos/wrong references etc. these might have to wait to be addressed. Thanks!

**Comment by sebffischer** [comment]
I forgot to do this, I guess these comments are now outdated.
