### ISSUE TITLE
Shorthand overview

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3book#518]
I could not see one, but I think this could be valuable:
Create an overview table for all of the shorthands we usually use, e.g. `tsk` etc. with the long form and a short explanation or return types.

**Comment by RaphaelS1** [comment]
These are being added to each chapter, see end of Chapter 4 for an example
<img width="737" alt="Screenshot 2023-01-26 at 11 34 00" src="https://user-images.githubusercontent.com/25639974/214825723-fad775e1-48a5-4b9b-a51b-400ca1d43da4.png">

We could combine all these into an appendix at the end if useful

**Comment by pfistfl** [comment]
Ah, then I might have missed it. 
Yeah, it might perhaps be good to collect all of them at the end?

**Comment by RaphaelS1** [comment]
Let's see once chapters are finished, it might make more sense to keep them separated so people know where to look for relevant sections -- closing for now as I think this will ultimately be a last minute design choice
