### ISSUE TITLE
Nested resampling description contains an error

### ISSUE THREAD

**Issue by FunWithForest** [mlr-org/mlr3book#53]
First of all thank you for creating mlr3 documentation. It really helps out a lot to understand its breaking changes compared to the older mlr version. Having checked the book at the tuning part here: https://mlr3book.mlr-org.com/tuning.html I recognized an error.
In the section 4.1.5 you state "Now the optimized hyperparameters can be used to create a new Learner and train it on the full dataset." Doing this step would only result in an overfitted model.
I tried it out to ensure the overfitting using a regression model and indeed the classification error of this model was then 0 while the last resampled model was at 0.03

Suggestion: 
After having defined a new learner with the optimized parameters paste 
learner$train(task, row_ids = train_set) to train the best model with the train set only to prevent overfitting.

**Comment by berndbischl** [comment]
1) thanks for having a look and providing feedback here. you are welcome to continue this :)

2) the book is far from being done and "in heavy development". we are currently working on version 0.1 of some packages (foremost: pipelines). then the book will come into more focused scope again. we are aiming for a "minimal" 0.1 version of the book in 2-3 months

3) answer for this issue: it is meant 

 "Now the optimized hyperparameters can be used to create a new Learner and train it on the full TRAINING dataset"

(in contrast to resampling the training set and only training on parts of it, as that is what happens during tuning)

but this should be clarififed, you are correct

**Comment by pat-s** [comment]
In my opinion, there is no error here.

First of all, the part you are talking about is in the "tuning" section, not the "nested resampling" section.

Second, the practice is correct as it is stated there:

1. Tune the params on a subset of the data using CV, aiming to receive the hyperpars which are most generalizable 
2. Use these hyperpars to train a model on the FULL dataset
3. Evaluate the model performance on a _external_ dataset

So, to clarify again:

Approach 1: Tuning + simple train/predict (train on the full task, predict on an external dataset)
Approach 2: Nested resampling: Tuning within the CV, train/predict on subsets of the task
