### ISSUE TITLE
"lrn" should be "learner" in below code - 

### ISSUE THREAD

**Issue by cmocheng** [mlr-org/mlr3book#532]
https://mlr3book.mlr-org.com/feature-selection.html 
Below contents was copied from the above book but I think the filter = flt("importance", learner = lrn) should be filter = flt("importance", learner = learner) 
--------------
task = tsk("penguins")
# Remove observations with missing data
task$filter(which(complete.cases(task$data())))
filter = flt("importance", learner = lrn)
filter$calculate(task)
as.data.table(filter)

**Comment by larskotthoff** [comment]
Thanks -- this is in fact correct. `lrn` refers to the learner that was created in the code chunk above.
