### ISSUE TITLE
Mini-issue: Wrong heading level in basics chapter :)

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr3book#533]
I think this should be a level 3 heading starting with ### and not a level 4 heading starting with ####
https://github.com/mlr-org/mlr3book/blob/379d8ed0cbc4845f6d87e4aee27942684815dadb/book/basics.qmd#L720

**Comment by larskotthoff** [comment]
Thanks -- this is actually intentional as a sub-heading for classification evaluation.
