### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/mlr3book#566]
The citation info is currently quite hidden in the `Preface`.

I would suggest having this findable from the landing page or at least a link to it in the `Appendix` (that was my initial guess on where to find it).

Furthermore, it might be sensible to provide citation info for each chapter at the end of the chapter.

**Comment by RaphaelS1** [comment]
Thanks. I'd also considered moving to Appendix. Citation info for each chapter will be discussed and decided by publisher
