### ISSUE TITLE
Summary issue for required / recommended software changes

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#575]
Some of the chapters might e.g. reference vignettes that don't yet exist. 
I intend this to be a summary issue, so these things are not forgotten once the book is published. Feel free to add things that fall into this category by editing this issue. 

* [x] Release `mlr3batchmark` to CRAN
* [x] Port the old paradox chapter as a vignette
* [x] Create a vignette that shows how to "Create a Tuner" in mlr3tuning (port from old extending chapter)
* [x] Create a vignette shat shows how to "Create a Learner" in mlr3extralearners (port from old extending chapter)
* [x] Create a vignette that shows how to "Add a PipeOp" in mlr3pipelines.
* [x] New `mlr3benchmark` release for function `as_benchmark_aggr()`

**Comment by be-marc** [comment]
- [ ] `mlr3verse` CRAN release for `tnr("hyperband")` and  `tnr("mbo")`
