### ISSUE TITLE
Preprocessing comments

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr3book#607]
- [x] Plots need captions.
- [x] URLs to custom CSVs are too long for the book.
- [x] Intro: I would only very briefly mention what is not covered here (feature selection) and talk more prominently about what this chapter does cover. At the moment the intro doesn't really make clear what the chapter is about. Could also consider renaming the chapter "Data Cleaning" or something like that.
- [x] .2: Too many tables and plots, and not using mlr3. I would remove all of the EDA and instead only list things to check for in data and then the result of those checks for this particular dataset to highlight the need for preprocessing (maybe illustrated with a few selected plots). Could even merge that into the other sections -- first illustrate the problem with a plot or two, then show what happens without preprocessing, then show the preprocessing.
- [x] .3: I would restructure this to first show the problem in each case (e.g. run SVM on categorical data, show it crash) and then the preprocessing step that solves it. At the moment there's a lot of text upfront and the code example later combines multiple things. I would start by showing the problem and then step by step build the pipeline that addresses the problems.
- [x] .4: Explain what `imputhist` does.
- [x] .4: I would mention a few more imputations, in particular imputing mean/median/mode, and the code for it.
- [x] .5: I would explicitly mention that this is the "sensible default" that should be used most of the time instead of doing it manually like in the previous two sections.
- [x] .6: Would remove the sentence about HPO at the end.
- [x] .7: I would give a little bit more introduction here -- where is this data coming from and why can't we just use it as-is?
- [x] .7: I would show the first few lines of the transformed data somewhere.
- [x] .7: In the last code example, mention why the pipeop is "trained" here and not part of the pipeline as in the previous examples.

**Comment by ja-thomas** [comment]
all addressed. Thanks for the comments
