### ISSUE TITLE
Preprocessing chapter references PipeOpTaskPreprocSimple that is not explained in the book

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3book#619]
https://github.com/mlr-org/mlr3book/blob/d0f69ac323434704dfdbd72ab54ae695b5f05602/book/preprocessing.qmd#L361

the PipeOpTaskPreprocSimple is not explained in the pipelines (or the extending) chapter any more, it was moved to a vignette in mlr3pipelines. The link would be https://mlr3pipelines.mlr-org.com/articles/extending.html#special-case-preprocessing-with-simple-train

**Comment by RaphaelS1** [comment]
Thank you, will fix this !

**Comment by RaphaelS1** [comment]
Closed in https://github.com/mlr-org/mlr3book/pull/608/commits/ef942d2358bf3379a46c7acb91d5d0691918a161
