### ISSUE TITLE
Optim comments/issues

### ISSUE THREAD

**Issue by sumny** [mlr-org/mlr3book#626]
Currently stumbled across a typo in the newly iterated and restructured optim section:

https://github.com/mlr-org/mlr3book/blob/7573a26750fe3c1245a14eb8141f0896a6030445/book/advanced_tuning.qmd#L134

Should read `<=` and `<` because we assume minimization

Will probably do another proofread pass on Monday so we might keep this issue open to see if we find more typos/errors.

**Comment by sumny** [comment]
Another issue:

* For some reason the Pareto front in Figure https://github.com/mlr-org/mlr3book/blob/7573a26750fe3c1245a14eb8141f0896a6030445/book/advanced_tuning.qmd#L182 only consists of a single point

**Comment by RaphaelS1** [comment]
Ahh great spot! Fixed first in this commit https://github.com/mlr-org/mlr3book/pull/601/commits/860e5839f727c55f02b143489359a258f6404d86

**Comment by RaphaelS1** [comment]
Fixed second here https://github.com/mlr-org/mlr3book/pull/628

**Comment by RaphaelS1** [comment]
https://github.com/mlr-org/mlr3book/pull/630 will also help fix second

**Comment by sumny** [comment]
Some more issues, others already addressed in this PR #643 

1. The manual log scaling is simply wrong I believe? https://mlr3book.mlr-org.com/optimization.html#sec-tune-trafo

We first show correctly:
```r
lrn("classif.svm", cost = to_tune(1e-5, 1e5, logscale = TRUE))$param_set$search_space()
```

this will automatically construct a numeric parameter tuned from 1e-5 to 1e5 on log scale, i.e., the bounds during sampling are log(1e-5) and log(1e5) and then we exp() those values.

then there is the following block:
```
To manually create the same transformation, we can pass the transformation to the `trafo` argument in `p_dbl`:

\```{r optimization-045}
ss = ps(cost = p_dbl(1e-5, 1e5, trafo = function(x) exp(x)))
ss
\```

In this case we do not see the transformation in the `lower` and `upper` fields, however we can confirm it is correctly set by making use of the `$trafo()` method, which takes a named list and applies the specified transformations

\```{r}
ss$trafo(list(cost = 1))
\```
```

This is not true. When setting this up manually, we *have* to manually transform the boundaries (correct me if I am wrong @be-marc or @sebffischer  but I am pretty sure) along with specifying the inverse transformation as the trafo to get the same search space on log-scale

i.e.,

we need to do:

```r
ss = ps(cost = p_dbl(log(1e-5), log(1e5), trafo = function(x) exp(x)))
```

we can also check this:

```r
range(generate_design_random(lrn("classif.svm", cost = to_tune(1e-5, 1e5, logscale = TRUE))$param_set$search_space(), 1000)$data)
```

```
[1] -11.46174  11.51102
```

```r
range(generate_design_random(ps(cost = p_dbl(1e-5, 1e5, trafo = function(x) exp(x))), 1000)$data)
```

```
[1]    52.4517 99948.4651
```

```r
range(generate_design_random(ps(cost = p_dbl(log(1e-5), log(1e5), trafo = function(x) exp(x))), 1000)$data)
```

```
[1] -11.51170  11.46398
```

Also, are we sure we want to name objects `ss`? ...


2. The examples here https://mlr3book.mlr-org.com/advanced_tuning.html no longer break down? (When illustrating encapsulation and runtime error)

**Comment by sumny** [comment]
3. ?fig-hyperband missing because eval=FALSE
4. ?fig-bayesian-sinusoidal_bo_rs missing because this section was dropped (though I believe some people really wanted to have something like such a plot in there to see that BO is actually better..)

**Comment by be-marc** [comment]
https://github.com/mlr-org/mlr3book/blob/7573a26750fe3c1245a14eb8141f0896a6030445/book/optimization.qmd#L414-L420

I think we should not show it like this. The complete tuning is lost except for the printed result. Storing in `instance` and printing `instance$result` adds one line of code.

**Comment by be-marc** [comment]
https://github.com/mlr-org/mlr3book/blob/667017bc0f2ee6d71d8c09221f4838d63b01ca5a/book/non_sequential_pipelines_and_tuning.qmd#L718-L726

This is also a strange way to show the results.

**Comment by sebffischer** [comment]
Search space  definition is imprecise https://github.com/mlr-org/mlr3book/blob/667017bc0f2ee6d71d8c09221f4838d63b01ca5a/book/optimization.qmd#L57

**Comment by sebffischer** [comment]
I think it is weird that we call it `<RangeTuneToken>` here: https://github.com/mlr-org/mlr3book/blob/667017bc0f2ee6d71d8c09221f4838d63b01ca5a/book/optimization.qmd#L82

**Comment by sebffischer** [comment]
https://github.com/mlr-org/mlr3book/blob/667017bc0f2ee6d71d8c09221f4838d63b01ca5a/book/optimization.qmd#L101

A specific time point is not the default parameter? 
Also this is error prone when we change the default parameters in the package.

**Comment by sebffischer** [comment]
Also in tuning we don't explain `Domain` objects at all. 
I am pretty sure there was an explanation of this before. Did we remove this intentionally?

**Comment by sebffischer** [comment]
Also do we explain that first the scalar trafos are being executed and then the `.extra_trafo`?

**Comment by sebffischer** [comment]
we mention the surv.coxtime learner but did not really talk about survival analysis yet

**Comment by sebffischer** [comment]
we use the `param_set$set_values(.values = ...)` which is not explained before.

**Comment by sebffischer** [comment]
We use `"evaluate"` encapsulation but don't explain what it is.

**Comment by sebffischer** [comment]
Also we use a `PipeOp` in advanced tuning but pipeops aren't really explained yet

**Comment by RaphaelS1** [comment]
@sumny I've addressed all your comments here https://github.com/mlr-org/mlr3book/pull/651/commits/91ab759facd6366d81ae1e7b680720e97930dca0

Re. dropped plots, this was discussed with BB

**Comment by RaphaelS1** [comment]
@be-marc addressed your first comment, re. 2nd I also dislike print out but the list takes up way too much space. Will think of a better alternative when I review the chapter, added a FIXME for now

**Comment by RaphaelS1** [comment]
> I think it is weird that we call it <RangeTuneToken> here: 

We frequently refer to output in the text, does look a bit weird but it's what's printed

> A specific time point is not the default parameter?
Also this is error prone when we change the default parameters in the package.

Table was completely wrong. Fixed and added 'at time of publication'

> Did we remove this intentionally?

Yes

> Also do we explain that first the scalar trafos are being executed and then the .extra_trafo?

Yes

> we mention the surv.coxtime learner but did not really talk about survival analysis yet

Took example from extralearners vignette as it's very common and provides a flexible template for vector tuning. Added a note to c.f survival 

> We use "evaluate" encapsulation but don't explain what it is.

Intentional. Keeping it brief until Technical

> Also we use a PipeOp in advanced tuning but pipeops aren't really explained yet

Moved to non-seq pipes

 All other comments addressed here https://github.com/mlr-org/mlr3book/pull/651
