### ISSUE TITLE
List of errors

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#644]
Here is a list of errors that I did not immediately fix: 

* https://mlr3book.mlr-org.com/performance.html#fig-resamp-viz-1 this is a barplot and not a histogram. What do we want here?

**Comment by larskotthoff** [comment]
But wait, this is actually a histogram, isn't it? Looks a bit weird because the bars don't touch, but definitely not a barplot.

**Comment by sebffischer** [comment]
You might be right. But at least the label of the y axis is wrong as histograms don't show counts.

**Comment by sebffischer** [comment]
Also the surfaces don't add up to 1 I think
