### ISSUE TITLE
Add a section about dictionaries (like mlr_learners etc)

### ISSUE THREAD

**Issue by mboecker** [mlr-org/mlr3book#69]
as requested in https://github.com/mlr-org/mlr3book/pull/65

**Comment by RaphaelS1** [comment]
Section should include https://github.com/mlr-org/mlr3book/issues/139

**Comment by RaphaelS1** [comment]
Should also include https://github.com/mlr-org/mlr3book/issues/199

**Comment by RaphaelS1** [comment]
And https://github.com/mlr-org/mlr3book/issues/259
