### ISSUE TITLE
Figure 3.14 got mixed up

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlr3book#691]
Currently, in the PDF version, Figure 3.14 is the following:
![image](https://github.com/mlr-org/mlr3book/assets/15801081/30b934ff-ed20-4843-8e09-077515970587)
This seems to be the same as Figure 3.13. In the non-BW version, this figure used to look like this:
![image](https://github.com/mlr-org/mlr3book/assets/15801081/df9910cd-09cc-4a28-a864-edb2cb8463b7)
The right one is now 3.15, but it looks like the left one should be 3.14?

**Comment by RaphaelS1** [comment]
@sebffischer was this fixed in your PR?

**Comment by sebffischer** [comment]
yes
