### ISSUE TITLE
Chapter 5 new exercises typos/issues

### ISSUE THREAD

**Issue by sumny** [mlr-org/mlr3book#704]
https://github.com/mlr-org/mlr3book/blob/75ee846c2d2d646cccc343ccc18e879d5f032117/book/chapters/chapter5/advanced_tuning_methods_and_black_box_optimization.qmd#L1120

Pareto-front should be Pareto front.
and $x_2 = \left(\sqrt{x_1}-2\right)^2$ with $x_1$ ranging from $0$ to $4$
should be $y_2 = \left(\sqrt{y_1}-2\right)^2$ with $y_1$ ranging from $0$ to $4$
because we are plotting the front, right?

**Comment by RaphaelS1** [comment]
@mb706 can you check above against exercises doc and make sure they're the same and PR a fix if needed please?

**Comment by sumny** [comment]
also the new Figure in 5.8 might be easier to visualize when either plotting 1-tpr and fpr or tpr and 1-fpr to either minimize or maximize both metrices.

**Comment by mb706** [comment]
the idea with the plot is that it looks like a roc plot
