### ISSUE TITLE
List of errors to fix in proofs

### ISSUE THREAD

**Issue by sebffischer** [mlr-org/mlr3book#720]
* [x] https://mlr3book.mlr-org.com/chapters/chapter8/non-sequential_pipelines_and_tuning.html#fig-pipelines-bagging -> should be `po("classifavg")` and not `po("classif.avg")`
* [x] https://github.com/mlr-org/mlr3book/pull/723 -> magrittr pipe used accidentally

**Comment by RaphaelS1** [comment]
* [ ] Update link to lockfile to reference version in tagged commit not main
* [ ] Add renv version to reproducibility section
