### ISSUE TITLE
[could not find function "as_task_regr_st"] error

### ISSUE THREAD

**Issue by mkganyago** [mlr-org/mlr3book#729]
Hello,

I getting an error "could not find function "as_task_regr_st". Is this implemented yet? or I am I using older versions of mlr3?
here are the versions loaded. 
mlr3extralearners_0.7.0-9000 
mlr3learners_0.5.4          
mlr3viz_0.5.10               
sf_1.0-8                    
terra_1.6-3                  
mlr3spatial_0.1.2           
mlr3verse_0.2.5              
mlr3_0.14.0                 

regards,
Mahlatse

**Comment by RaphaelS1** [comment]
You need to load `mlr3spatiotempcv`

See: https://mlr3book.mlr-org.com/chapters/chapter13/beyond_regression_and_classification.html#taskclassifst-and-taskregrst

**Comment by mkganyago** [comment]
Thank you very much @RaphaelS1.
