### ISSUE TITLE
Core: mlr -> mlr3 transition table

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3book#8]

**Comment by pat-s** [comment]
@mboecker 	The issue is not done even though I merged #11 	

This is just a first draft that we should use as a base to continue on.

**Comment by mllg** [comment]
The table is outdated, much of the functionality is now implemented. Also, it would be nice to have links in the table.

**Comment by pat-s** [comment]
This is a student assistant task. Added it to the doc.

**Comment by mllg** [comment]
Output was also broken. Moved to attic until it is fixed with regard to its contents.

**Comment by pat-s** [comment]
I think it's not needed anymore.
