### ISSUE TITLE
Section on custom pipelines

### ISSUE THREAD

**Issue by MislavSag** [mlr-org/mlr3book#800]
I am trying to find sections on custom pipelines in mlr3book, but I can't find hem. 

Is there any good reason for that? 

I used to return to those sections when I was developing my pipelines.

**Comment by sebffischer** [comment]
The chapter is now a vignette in `mlr3pipelines`, unfortunately it is currently not shown on the pkgdown site, so you can either access it through github: https://github.com/mlr-org/mlr3pipelines/blob/master/vignettes/extending.Rmd or via R. 

I already created a PR in pipelines for the pkgdown issue here: https://github.com/mlr-org/mlr3pipelines/pull/745
