### ISSUE TITLE
Chapter 4.1 Example bug

### ISSUE THREAD

**Issue by einabadi-sh** [mlr-org/mlr3book#811]
This is the first example of model tuning in chapter 4.1. Despite attempting it with various settings, I continually encounter the same error. It appears that the function might not be supplying the correct data frame to the predictor.

```
library(mlr3verse)
tsk_sonar = tsk("sonar")

learner = lrn("classif.svm",
              cost  = to_tune(1e-1, 1e5),
              gamma = to_tune(1e-1, 1),
              kernel = "radial",
              type = "C-classification"
)

instance = ti(
  task = tsk_sonar,
  learner = learner,
  resampling = rsmp("cv", folds = 3),
  measures = msr("classif.ce"),
  terminator = trm("none")
)

tuner = tnr("grid_search", resolution = 5, batch_size = 10)
tuner$optimize(instance)

```

> **Error in predict.svm(self$model, newdata = newdata, probability = (self$predict_type ==  : 
>   test data does not match model !**
>

**Comment by larskotthoff** [comment]
Works for me. Can you post your package versions please?

**Comment by einabadi-sh** [comment]
Ubuntu 22.04.3 LTS

> R.version.string
>[1] "R version 4.3.2 (2023-10-31)"

> packageVersion("mlr3verse")
> [1] ‘0.2.8’

Thanks

**Comment by larskotthoff** [comment]
Same version here. What about the other packages?

**Comment by einabadi-sh** [comment]
![Screenshot from 2024-01-26 16-55-46](https://github.com/mlr-org/mlr3book/assets/27699259/265aef9e-d8ec-46f5-9e16-0c1c2f069711)

**Comment by einabadi-sh** [comment]
> packageVersion("e1071")
> [1] ‘1.7.13’

**Comment by larskotthoff** [comment]
Looks like you installed some github versions? Can you try the latest CRAN versions please?

**Comment by einabadi-sh** [comment]
<img width="1261" alt="Screenshot 2024-01-26 at 6 28 43 PM" src="https://github.com/mlr-org/mlr3book/assets/27699259/bf541986-46bb-437b-9f51-17ae108790ea">

**Comment by einabadi-sh** [comment]
thanks, now it works!
