### ISSUE TITLE
Preprocessing chapter broken after Ames dataset move

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr3book#843]
Chapter 9 (Preprocessing) relies on the Ames Housing dataset, which was just removed from mlr3data and put into mlr3. The version in mlr3 is a cleaned up version though that doesn't have the issues that the chapter shows how to solve. The original dataset from the AmesHousing package also doesn't seem to have these issues.

Is there another place where we can get the raw data from? Or include with the mlr3book package.

**Comment by be-marc** [comment]
Sorry. I'll just undo that.

**Comment by be-marc** [comment]
You can use `mlr-org/mlr3data` for now. I will upload the version with ames housing to CRAN next week.

**Comment by be-marc** [comment]
mlr3data 0.9.0 is on CRAN
