### ISSUE TITLE
Survival example fails

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr3book#844]
Getting

````
Error:
! Cannot set argument 'gamma.mu' for 'LearnerSurvSVM' (not a constructor argument, not a parameter, not a field.
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 16. base::withRestarts(...)
 17. base (local) withRestartList(expr, restarts)
 18. base (local) withOneRestart(withRestartList(expr, restarts[-nr]), restarts[[nr]])
 19. base (local) docall(restart$handler, restartArgs)
 21. evaluate (local) fun(base::quote(`<smplErrr>`))



Quitting from lines 261-266 [special-016] (beyond_regression_and_classification.qmd)
Execution halted
````

The text says that `gamma.mu` is a required argument, but apparently it is not anymore? Looks like it was split into two hyperparameters @sebffischer @bblodfon

**Comment by bblodfon** [comment]
Yes, we split it so that we could tune both separately for the benchmark paper @jemus42 is working on. 

The survival chapter needs a few updates, I should work on a revision/review I guess?

**Comment by larskotthoff** [comment]
That would be great, thanks. I'm still trying to put together a docker container for the book build, and this chapter is currently the holdup.

**Comment by larskotthoff** [comment]
Fixed in #850

**Comment by sebffischer** [comment]
the book still fails

**Comment by larskotthoff** [comment]
Working on that.
