### ISSUE TITLE
Error in resampling a graph

### ISSUE THREAD

**Issue by christian43** [mlr-org/mlr3book#847]
Hi, I got this error when running my script. 

Fehler in learner$validate <- validate : kann keine Bindungen zu einer abgeschlossenen Umgebung hinzufügen

The resampling process starts normal. After some rounds it stops with the error.

rr <- resample(
  task = task,
  learner = auto_tuner_xgboost,
  resampling = outer_cv,
  store_models = TRUE
)

**Comment by larskotthoff** [comment]
Have you tried with the latest package versions? This should be fixed.

**Comment by christian43** [comment]
ohh - that it was. Sorry for stealing your time and thanks
