### ISSUE TITLE
error in learner$predict_newdata()

### ISSUE THREAD

**Issue by christian43** [mlr-org/mlr3book#849]
Dear MLR3-Team, 

i trained a graph including a xgboost model. Now using learner$predict_newdata(data), where data is a data frame and contains no target column and get the following error.

Fehler: Setting row roles 'test'/'holdout' is no longer possible.

Any suggestions how to proceed? 

best regards christian

**Comment by christian43** [comment]
This is how I trained the model...

library(mlr3)
library(mlr3tuningspaces)
library(mlr3tuning)
library(mlr3learners)
library(mlr3extralearners)
library(mlr3pipelines)

set.seed(563)


task <- tsk("spam")

outer_cv <- rsmp("cv", folds = 5)
inner_cv <- rsmp("cv", folds = 3)

msr_se <- msr("classif.auc")

po_over <- po("classbalancing",
              id = "oversample",
              adjust = "minor",
              reference = "minor",
              shuffle = TRUE,
              ratio = to_tune(1, 6))

tuning_space <- lts("classif.xgboost.default")

po_lrn_xgboost <- tuning_space$get_learner(predict_type = "prob")


glrn_xgboost <- as_learner(po_over %>>% ppl("robustify") %>>% po_lrn_xgboost) 
glrn_xgboost$id = "XGBoost"
auto_tuner_xgboost <- auto_tuner(tuner = tnr("random_search"),
                                learner = glrn_xgboost,
                                resampling = inner_cv,
                                measure = msr_se,
                                terminator = trm("run_time", secs = 5))

rr <- resample(
  task = task,
  learner = auto_tuner_xgboost,
  resampling = outer_cv,
  store_models = TRUE
)


mod_xgboost <- auto_tuner_xgboost$train(task)


saveRDS(glrn_xgboost, file = "glrnxgboost.rds")

learner <- readRDS("temp/glrnxgboost.rds")
pred <- learner$predict_newdata(new)

**Comment by be-marc** [comment]
Why do you save the `GraphLearner` instead of the trained `AutoTuner`?

**Comment by be-marc** [comment]
This is not a working example. `new` is not defined.

**Comment by be-marc** [comment]
It could be this issue https://mlr-org.com/faq.html#old-model-broken

**Comment by christian43** [comment]
yes you are right... running this code with new defined as subset of task data works fine and saving the graph is a typo, sorry. I am going to update all and run the code again. thank you for your time
