### ISSUE TITLE
2.7.2 Binary classification - Threshold Tuning incomplete 

### ISSUE THREAD

**Issue by danielsaggau** [mlr-org/mlr3book#85]
Section needs to be extended. 

current content: 
"When we are interested in class labels based on scores or probabilities, we can set the classification threshold according to our target performance measure.
This threshold however can also be **tuned**, since the optimal threshold might differ for different (custom) measures or in situations like const-sensitive classification.

This can be also done with `mlr3`."

**Comment by mllg** [comment]
Continued in #117 .
