### ISSUE TITLE
Unclear Parameter Tuning Defaults

### ISSUE THREAD

**Issue by DarioS** [mlr-org/mlr3book#852]
In Chapter 4: Hyperparameter Optimization, I found it difficult to understand if any parameter tuning happens by default. It could be stated in one sentence in the introduction before going deep into the details of creating one. I know that caret has a default grid of values for each classifier, but I am hoping to understand what the philosophy of mlr3 is from the textbook.

**Comment by larskotthoff** [comment]
Do you mean if mlr3 does any tuning without you explicitly setting it up? Or do you mean any automatic definitions of hyperparameter tuning spaces?

**Comment by DarioS** [comment]
Any tuning happening without a user explicitly requesting it.

**Comment by larskotthoff** [comment]
Ok, no tuning ever happens without the user explicitly doing it. I'll add a sentence to that effect.
