### ISSUE TITLE
PDF: Consider using pinp output format

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3book#89]
I've just added basic support for the [pinp](https://github.com/eddelbuettel/pinp) output format for PDF to the book

```
make pinp
```

Overall it looks much more professional than `bookdown::pdf_book()`. Though it needs some fine tuning. Also figures are oversized right now.

Maybe @eddelbuettel could take a look and provide some pointers based on his expertise? :)

**Comment by eddelbuettel** [comment]
Interesting.  Never considered `pinp` for a book.

I am running into issues though. Neither `make pdf` nor `make pinp` complete for me right now.

**Comment by pat-s** [comment]
It did for me. Can you share the log?

Also pinp options are honored when set in `index.Rmd` and do not affect other output formats:

https://github.com/mlr-org/mlr3book/blob/25d03a24b1052592493ea365a50adc37bdc306a4/bookdown/index.Rmd#L17-L21

**Comment by eddelbuettel** [comment]
> Can you share the log?

It is essentially once again `tinytex` getting in the way.  Can you remind me how to decompose the `bookdown::render()` call to "just" get the latexing command?

So for `make pinp` I just die on `tinytex`:

```sh
[.... lots of stuff omitted ...]

output file: mlr3book.knit.md

/home/edd/bin/pandoc +RTS -K512m -RTS mlr3book.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output mlr3book.tex --template /usr/local/lib/R/site-library/pinp/rmarkdown/templates/pdf/resources/template.tex --highlight-style tango --pdf-engine pdflatex --natbib --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmd/lua/latex-div.lua --include-in-header /tmp/RtmpPsWCWw/rmarkdown-str4fa045a5dc70.html 
tlmgr search --file --global '/tikzlibrarytopaths.code.tex'
Cannot determine type of tlpdb from /home/edd/texmf!
tlmgr: running in usermode, did you call `tlmgr init-usertree'?
! LaTeX Error: Environment warning undefined.

Error: Failed to compile mlr3book.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See mlr3book.log for more info.
In addition: There were 12 warnings (use warnings() to see them)
Execution halted
make: *** [Makefile:30: pinp] Error 1
edd@rob:~/git/mlr3book(master)$ 
```

For `make pdf` I get 

```
/home/edd/bin/pandoc +RTS -K512m -RTS mlr3book.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output mlr3book.tex --table-of-contents --toc-depth 4 --template /usr/local/lib/R/
site-library/rmarkdown/rmd/latex/default-1.17.0.2.tex --number-sections --highlight-style haddock --pdf-engine xelatex --natbib --include-in-header preamble.tex --variable graphics=yes --lua-filter /usr/local/li
b/R/site-library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmd/lua/latex-div.lua --wrap preserve --variable 'compact-title:yes' --include-in-header /tmp/RtmpRN1dig/rmar
kdown-str6ce726038bb7.html --variable tables=yes --standalone
! Undefined control sequence.
l.24 \pgfsyspdfmark                                         
                    {pgfid1}{3411406}{29920516}         
                               
Error: Failed to compile mlr3book.tex. See https://yihui.name/tinytex/r/#debugging for debugging tips. See mlr3book.log for more info.
In addition: Warning messages:
```

Ok, a quick google search lead to [this post at tex.stackexchange.com](https://tex.stackexchange.com/questions/319983/undefined-control-sequence-pgfsyspdfmark-converting-standalone-tikz-with-pdflat) and this diff:

```diff
edd@rob:~/git/mlr3book(master)$ git diff bookdown/preamble.tex
diff --git a/bookdown/preamble.tex b/bookdown/preamble.tex
index f918a0a..83c78cc 100644
--- a/bookdown/preamble.tex
+++ b/bookdown/preamble.tex
@@ -4,6 +4,7 @@
 \usepackage[paperwidth=6in, paperheight=9in]{geometry}
 
 % \setmainfont[UprightFeatures={SmallCapsFont=AlegreyaSC-Regular}]{Alegreya}
+\providecommand{\pgfsyspdfmark}[3]{}
 
 % Subtract 1 from counters that are used
 \renewcommand{\thesection}{\thechapter.\number\numexpr\value{section}-1\relax}
edd@rob:~/git/mlr3book(master)$ 
```

I have fought `tinytex` in the past with little luck. I generally don't need it on Ubuntu, but when it gets in the way it really effs things up.

**Comment by eddelbuettel** [comment]
I went incremental "hiding the various chapters but 01.  Adding 02 works,  adding 03 fails.  The resulting tex file does not have  the `preamp.tex` included.  Is that our error in how we use bookdown?

**Comment by pat-s** [comment]
That's odd.

I maybe wrong here but aren't you failing on the `pandoc` call?

```
/home/edd/bin/pandoc +RTS -K512m -RTS mlr3book.utf8.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output mlr3book.tex --template /usr/local/lib/R/site-library/pinp/rmarkdown/templates/pdf/resources/template.tex --highlight-style tango --pdf-engine pdflatex --natbib --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /usr/local/lib/R/site-library/rmarkdown/rmd/lua/latex-div.lua --include-in-header /tmp/RtmpPsWCWw/rmarkdown-str4fa045a5dc70.html 
tlmgr search --file --global '/tikzlibrarytopaths.code.tex'
```

Idk if `tinytex` comes in the way here but could it be that your pandoc version is too old maybe? I am on v2.7.3.

Unrelated to the failre, do you have a `.tex` output in your dir? Even when failing I get a `.tex` in the working dir. This errors when calling `pdflatex` from the command line but it works when clicking the "compile pdf" button in RStudio 😆 

In any case, lot's to do to get this one robust. Finally we will have the PDF being built on the CI worker anyways. Nevertheless, local compilation should work.

---

The "environment undefined" thing relates to the Rmd "warning" and "caution" blocks from bookdown. There is a workaround in an issue that I already applied for the pdf book (which stopped working at some point). I probably need to add it specifically to the pinp version or check the proper inclusion of `preamble.tex`.

You're free to help ofc though I fully understand that you want to wait until we have a somewhat robust pinp implementation running to contribute to the details.

**Comment by eddelbuettel** [comment]
I have pandoc 2.2.1 from Ubuntu and 2.3.1 from RStudio.  That should be sufficient.  

The errors all seem to come from your end.  I "hit" mabe 5% success in all the trials I had yesterday and today and find that a little frustrating.  

I have to work on other stuff now so I have to leave this to you for now.

**Comment by eddelbuettel** [comment]
> aren't you failing on the pandoc call?

Maybe?  But it dies 'texing' and I do have a log from *tex processing.  And as I said, at least sometimes the preamp.tex does not make it into the file it tries to render --> looks like a setup issue in the processing pipeline, no?

**Comment by mllg** [comment]
`pinp` cannot work in the way it is currently interfaced. The preamble will not get included (as Dirk reported) without a section in the `_output.yaml` for `pinp`.

We should first focus on rendering via `bookdown::pdf_book()` and robustify this, i.e. by setting up a travis job.

**Comment by eddelbuettel** [comment]
Thanks for the cleanup. I still _must_ add the one line to `preamble.tex` to add a missing definition, and add the other as a preference for the ink/paper ratio:

```diff
edd@rob:~/git/mlr3book(master)$ git diff bookdown/preamble.tex
diff --git a/bookdown/preamble.tex b/bookdown/preamble.tex
index ec7b00b..b7dc01a 100644
--- a/bookdown/preamble.tex
+++ b/bookdown/preamble.tex
@@ -1,9 +1,11 @@
 \usepackage{booktabs}
 \usepackage{longtable}
 \usepackage[bf,singlelinecheck=off]{caption}
-\usepackage[paperwidth=6in, paperheight=9in]{geometry}
+%\usepackage[paperwidth=6in, paperheight=9in]{geometry}
+\usepackage[margin=1in]{geometry}
 
 % \setmainfont[UprightFeatures={SmallCapsFont=AlegreyaSC-Regular}]{Alegreya}
+\providecommand{\pgfsyspdfmark}[3]{}
 
 % Subtract 1 from counters that are used
 \renewcommand{\thesection}{\thechapter.\number\numexpr\value{section}-1\relax}
edd@rob:~/git/mlr3book(master)$ 
```

**Comment by mllg** [comment]
Thanks, Dirk, we will figure this out with Travis and ping you as soon as we have found a better solution.

**Comment by eddelbuettel** [comment]
Again, nicely done, Michel!  It reads pretty well now (and I remain adamant about the `geometry` change: too few words per page in the default).

**Comment by mllg** [comment]
Getting one PDF output right is already hard enough. Closing here.
