### ISSUE TITLE
Bullet point hirarchy is not preserved

### ISSUE THREAD

**Issue by adibender** [mlr-org/mlr3book#96]
For example: https://mlr3book.mlr-org.com/ext-learner.html#ext-learner

I see: 
![image](https://user-images.githubusercontent.com/1672665/69720816-c5df0680-1113-11ea-9da8-2c920fb653f6.png)

Locally served book looks fine.

**Comment by mllg** [comment]
Looks like a pandoc problem. If this is the case, #98 should solve this. Will investigate.

**Comment by mllg** [comment]
Should be fixed now.
