### ISSUE TITLE
Collect use cases in notebooks?

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3book#99]
Pro:

* Keeps the book small and maintainable.
* Easier to work with.

Cons:

No CI / custom CI job.

**Comment by pat-s** [comment]
What kind of notebooks?

> No CI / custom CI job.

This can certainly be handled, even with pushing to the existing pkgdown site (as external links then).

**Comment by jakob-r** [comment]
We collect use cases in https://github.com/mlr-org/mlr3gallery/
